ALTER TABLE organizations ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS deleted_at BIGINT DEFAULT 0;
