// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/project/model"
	mock "github.com/stretchr/testify/mock"
)

// MockProjectUseCase is an autogenerated mock type for the ProjectUseCase type
type MockProjectUseCase struct {
	mock.Mock
}

type MockProjectUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectUseCase) EXPECT() *MockProjectUseCase_Expecter {
	return &MockProjectUseCase_Expecter{mock: &_m.Mock}
}

// CreateProject provides a mock function with given fields: ctx, userID, orgID, req
func (_m *MockProjectUseCase) CreateProject(ctx context.Context, userID string, orgID string, req model.CreateProjectRequest) (*model.ProjectResponse, error) {
	ret := _m.Called(ctx, userID, orgID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 *model.ProjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.CreateProjectRequest) (*model.ProjectResponse, error)); ok {
		return rf(ctx, userID, orgID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.CreateProjectRequest) *model.ProjectResponse); ok {
		r0 = rf(ctx, userID, orgID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, model.CreateProjectRequest) error); ok {
		r1 = rf(ctx, userID, orgID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectUseCase_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockProjectUseCase_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - orgID string
//   - req model.CreateProjectRequest
func (_e *MockProjectUseCase_Expecter) CreateProject(ctx interface{}, userID interface{}, orgID interface{}, req interface{}) *MockProjectUseCase_CreateProject_Call {
	return &MockProjectUseCase_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, userID, orgID, req)}
}

func (_c *MockProjectUseCase_CreateProject_Call) Run(run func(ctx context.Context, userID string, orgID string, req model.CreateProjectRequest)) *MockProjectUseCase_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(model.CreateProjectRequest))
	})
	return _c
}

func (_c *MockProjectUseCase_CreateProject_Call) Return(_a0 *model.ProjectResponse, _a1 error) *MockProjectUseCase_CreateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectUseCase_CreateProject_Call) RunAndReturn(run func(context.Context, string, string, model.CreateProjectRequest) (*model.ProjectResponse, error)) *MockProjectUseCase_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function with given fields: ctx, id
func (_m *MockProjectUseCase) DeleteProject(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectUseCase_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockProjectUseCase_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProjectUseCase_Expecter) DeleteProject(ctx interface{}, id interface{}) *MockProjectUseCase_DeleteProject_Call {
	return &MockProjectUseCase_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, id)}
}

func (_c *MockProjectUseCase_DeleteProject_Call) Run(run func(ctx context.Context, id string)) *MockProjectUseCase_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProjectUseCase_DeleteProject_Call) Return(_a0 error) *MockProjectUseCase_DeleteProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectUseCase_DeleteProject_Call) RunAndReturn(run func(context.Context, string) error) *MockProjectUseCase_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectByID provides a mock function with given fields: ctx, id
func (_m *MockProjectUseCase) GetProjectByID(ctx context.Context, id string) (*model.ProjectResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectByID")
	}

	var r0 *model.ProjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.ProjectResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.ProjectResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectUseCase_GetProjectByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectByID'
type MockProjectUseCase_GetProjectByID_Call struct {
	*mock.Call
}

// GetProjectByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProjectUseCase_Expecter) GetProjectByID(ctx interface{}, id interface{}) *MockProjectUseCase_GetProjectByID_Call {
	return &MockProjectUseCase_GetProjectByID_Call{Call: _e.mock.On("GetProjectByID", ctx, id)}
}

func (_c *MockProjectUseCase_GetProjectByID_Call) Run(run func(ctx context.Context, id string)) *MockProjectUseCase_GetProjectByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProjectUseCase_GetProjectByID_Call) Return(_a0 *model.ProjectResponse, _a1 error) *MockProjectUseCase_GetProjectByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectUseCase_GetProjectByID_Call) RunAndReturn(run func(context.Context, string) (*model.ProjectResponse, error)) *MockProjectUseCase_GetProjectByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjects provides a mock function with given fields: ctx, orgID
func (_m *MockProjectUseCase) GetProjects(ctx context.Context, orgID string) ([]*model.ProjectResponse, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetProjects")
	}

	var r0 []*model.ProjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.ProjectResponse, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.ProjectResponse); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ProjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectUseCase_GetProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjects'
type MockProjectUseCase_GetProjects_Call struct {
	*mock.Call
}

// GetProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockProjectUseCase_Expecter) GetProjects(ctx interface{}, orgID interface{}) *MockProjectUseCase_GetProjects_Call {
	return &MockProjectUseCase_GetProjects_Call{Call: _e.mock.On("GetProjects", ctx, orgID)}
}

func (_c *MockProjectUseCase_GetProjects_Call) Run(run func(ctx context.Context, orgID string)) *MockProjectUseCase_GetProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProjectUseCase_GetProjects_Call) Return(_a0 []*model.ProjectResponse, _a1 error) *MockProjectUseCase_GetProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectUseCase_GetProjects_Call) RunAndReturn(run func(context.Context, string) ([]*model.ProjectResponse, error)) *MockProjectUseCase_GetProjects_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function with given fields: ctx, id, req
func (_m *MockProjectUseCase) UpdateProject(ctx context.Context, id string, req model.UpdateProjectRequest) (*model.ProjectResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 *model.ProjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.UpdateProjectRequest) (*model.ProjectResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.UpdateProjectRequest) *model.ProjectResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProjectResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.UpdateProjectRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectUseCase_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockProjectUseCase_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req model.UpdateProjectRequest
func (_e *MockProjectUseCase_Expecter) UpdateProject(ctx interface{}, id interface{}, req interface{}) *MockProjectUseCase_UpdateProject_Call {
	return &MockProjectUseCase_UpdateProject_Call{Call: _e.mock.On("UpdateProject", ctx, id, req)}
}

func (_c *MockProjectUseCase_UpdateProject_Call) Run(run func(ctx context.Context, id string, req model.UpdateProjectRequest)) *MockProjectUseCase_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.UpdateProjectRequest))
	})
	return _c
}

func (_c *MockProjectUseCase_UpdateProject_Call) Return(_a0 *model.ProjectResponse, _a1 error) *MockProjectUseCase_UpdateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectUseCase_UpdateProject_Call) RunAndReturn(run func(context.Context, string, model.UpdateProjectRequest) (*model.ProjectResponse, error)) *MockProjectUseCase_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectUseCase creates a new instance of MockProjectUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectUseCase {
	mock := &MockProjectUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
