linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: internal/router/tus_docs.go
      linters:
        - unused
