// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/organization/model"
	mock "github.com/stretchr/testify/mock"
)

// MockOrganizationUseCase is an autogenerated mock type for the OrganizationUseCase type
type MockOrganizationUseCase struct {
	mock.Mock
}

type MockOrganizationUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationUseCase) EXPECT() *MockOrganizationUseCase_Expecter {
	return &MockOrganizationUseCase_Expecter{mock: &_m.Mock}
}

// CreateOrganization provides a mock function with given fields: ctx, userID, request
func (_m *MockOrganizationUseCase) CreateOrganization(ctx context.Context, userID string, request *model.CreateOrganizationRequest) (*model.OrganizationResponse, error) {
	ret := _m.Called(ctx, userID, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 *model.OrganizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.CreateOrganizationRequest) (*model.OrganizationResponse, error)); ok {
		return rf(ctx, userID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.CreateOrganizationRequest) *model.OrganizationResponse); ok {
		r0 = rf(ctx, userID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrganizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.CreateOrganizationRequest) error); ok {
		r1 = rf(ctx, userID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationUseCase_CreateOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganization'
type MockOrganizationUseCase_CreateOrganization_Call struct {
	*mock.Call
}

// CreateOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - request *model.CreateOrganizationRequest
func (_e *MockOrganizationUseCase_Expecter) CreateOrganization(ctx interface{}, userID interface{}, request interface{}) *MockOrganizationUseCase_CreateOrganization_Call {
	return &MockOrganizationUseCase_CreateOrganization_Call{Call: _e.mock.On("CreateOrganization", ctx, userID, request)}
}

func (_c *MockOrganizationUseCase_CreateOrganization_Call) Run(run func(ctx context.Context, userID string, request *model.CreateOrganizationRequest)) *MockOrganizationUseCase_CreateOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.CreateOrganizationRequest))
	})
	return _c
}

func (_c *MockOrganizationUseCase_CreateOrganization_Call) Return(_a0 *model.OrganizationResponse, _a1 error) *MockOrganizationUseCase_CreateOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationUseCase_CreateOrganization_Call) RunAndReturn(run func(context.Context, string, *model.CreateOrganizationRequest) (*model.OrganizationResponse, error)) *MockOrganizationUseCase_CreateOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrganization provides a mock function with given fields: ctx, id, userID
func (_m *MockOrganizationUseCase) DeleteOrganization(ctx context.Context, id string, userID string) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrganizationUseCase_DeleteOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrganization'
type MockOrganizationUseCase_DeleteOrganization_Call struct {
	*mock.Call
}

// DeleteOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockOrganizationUseCase_Expecter) DeleteOrganization(ctx interface{}, id interface{}, userID interface{}) *MockOrganizationUseCase_DeleteOrganization_Call {
	return &MockOrganizationUseCase_DeleteOrganization_Call{Call: _e.mock.On("DeleteOrganization", ctx, id, userID)}
}

func (_c *MockOrganizationUseCase_DeleteOrganization_Call) Run(run func(ctx context.Context, id string, userID string)) *MockOrganizationUseCase_DeleteOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOrganizationUseCase_DeleteOrganization_Call) Return(_a0 error) *MockOrganizationUseCase_DeleteOrganization_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrganizationUseCase_DeleteOrganization_Call) RunAndReturn(run func(context.Context, string, string) error) *MockOrganizationUseCase_DeleteOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganization provides a mock function with given fields: ctx, id
func (_m *MockOrganizationUseCase) GetOrganization(ctx context.Context, id string) (*model.OrganizationResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganization")
	}

	var r0 *model.OrganizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.OrganizationResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.OrganizationResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrganizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationUseCase_GetOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganization'
type MockOrganizationUseCase_GetOrganization_Call struct {
	*mock.Call
}

// GetOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrganizationUseCase_Expecter) GetOrganization(ctx interface{}, id interface{}) *MockOrganizationUseCase_GetOrganization_Call {
	return &MockOrganizationUseCase_GetOrganization_Call{Call: _e.mock.On("GetOrganization", ctx, id)}
}

func (_c *MockOrganizationUseCase_GetOrganization_Call) Run(run func(ctx context.Context, id string)) *MockOrganizationUseCase_GetOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrganizationUseCase_GetOrganization_Call) Return(_a0 *model.OrganizationResponse, _a1 error) *MockOrganizationUseCase_GetOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationUseCase_GetOrganization_Call) RunAndReturn(run func(context.Context, string) (*model.OrganizationResponse, error)) *MockOrganizationUseCase_GetOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationBySlug provides a mock function with given fields: ctx, slug
func (_m *MockOrganizationUseCase) GetOrganizationBySlug(ctx context.Context, slug string) (*model.OrganizationResponse, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationBySlug")
	}

	var r0 *model.OrganizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.OrganizationResponse, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.OrganizationResponse); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrganizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationUseCase_GetOrganizationBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationBySlug'
type MockOrganizationUseCase_GetOrganizationBySlug_Call struct {
	*mock.Call
}

// GetOrganizationBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockOrganizationUseCase_Expecter) GetOrganizationBySlug(ctx interface{}, slug interface{}) *MockOrganizationUseCase_GetOrganizationBySlug_Call {
	return &MockOrganizationUseCase_GetOrganizationBySlug_Call{Call: _e.mock.On("GetOrganizationBySlug", ctx, slug)}
}

func (_c *MockOrganizationUseCase_GetOrganizationBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockOrganizationUseCase_GetOrganizationBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrganizationUseCase_GetOrganizationBySlug_Call) Return(_a0 *model.OrganizationResponse, _a1 error) *MockOrganizationUseCase_GetOrganizationBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationUseCase_GetOrganizationBySlug_Call) RunAndReturn(run func(context.Context, string) (*model.OrganizationResponse, error)) *MockOrganizationUseCase_GetOrganizationBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserOrganizations provides a mock function with given fields: ctx, userID
func (_m *MockOrganizationUseCase) GetUserOrganizations(ctx context.Context, userID string) (*model.UserOrganizationsResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrganizations")
	}

	var r0 *model.UserOrganizationsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserOrganizationsResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserOrganizationsResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserOrganizationsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationUseCase_GetUserOrganizations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserOrganizations'
type MockOrganizationUseCase_GetUserOrganizations_Call struct {
	*mock.Call
}

// GetUserOrganizations is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockOrganizationUseCase_Expecter) GetUserOrganizations(ctx interface{}, userID interface{}) *MockOrganizationUseCase_GetUserOrganizations_Call {
	return &MockOrganizationUseCase_GetUserOrganizations_Call{Call: _e.mock.On("GetUserOrganizations", ctx, userID)}
}

func (_c *MockOrganizationUseCase_GetUserOrganizations_Call) Run(run func(ctx context.Context, userID string)) *MockOrganizationUseCase_GetUserOrganizations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrganizationUseCase_GetUserOrganizations_Call) Return(_a0 *model.UserOrganizationsResponse, _a1 error) *MockOrganizationUseCase_GetUserOrganizations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationUseCase_GetUserOrganizations_Call) RunAndReturn(run func(context.Context, string) (*model.UserOrganizationsResponse, error)) *MockOrganizationUseCase_GetUserOrganizations_Call {
	_c.Call.Return(run)
	return _c
}

// HardDeleteOrganization provides a mock function with given fields: ctx, id
func (_m *MockOrganizationUseCase) HardDeleteOrganization(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for HardDeleteOrganization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrganizationUseCase_HardDeleteOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HardDeleteOrganization'
type MockOrganizationUseCase_HardDeleteOrganization_Call struct {
	*mock.Call
}

// HardDeleteOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrganizationUseCase_Expecter) HardDeleteOrganization(ctx interface{}, id interface{}) *MockOrganizationUseCase_HardDeleteOrganization_Call {
	return &MockOrganizationUseCase_HardDeleteOrganization_Call{Call: _e.mock.On("HardDeleteOrganization", ctx, id)}
}

func (_c *MockOrganizationUseCase_HardDeleteOrganization_Call) Run(run func(ctx context.Context, id string)) *MockOrganizationUseCase_HardDeleteOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrganizationUseCase_HardDeleteOrganization_Call) Return(_a0 error) *MockOrganizationUseCase_HardDeleteOrganization_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrganizationUseCase_HardDeleteOrganization_Call) RunAndReturn(run func(context.Context, string) error) *MockOrganizationUseCase_HardDeleteOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreOrganization provides a mock function with given fields: ctx, id
func (_m *MockOrganizationUseCase) RestoreOrganization(ctx context.Context, id string) (*model.OrganizationResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RestoreOrganization")
	}

	var r0 *model.OrganizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.OrganizationResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.OrganizationResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrganizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationUseCase_RestoreOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreOrganization'
type MockOrganizationUseCase_RestoreOrganization_Call struct {
	*mock.Call
}

// RestoreOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrganizationUseCase_Expecter) RestoreOrganization(ctx interface{}, id interface{}) *MockOrganizationUseCase_RestoreOrganization_Call {
	return &MockOrganizationUseCase_RestoreOrganization_Call{Call: _e.mock.On("RestoreOrganization", ctx, id)}
}

func (_c *MockOrganizationUseCase_RestoreOrganization_Call) Run(run func(ctx context.Context, id string)) *MockOrganizationUseCase_RestoreOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrganizationUseCase_RestoreOrganization_Call) Return(_a0 *model.OrganizationResponse, _a1 error) *MockOrganizationUseCase_RestoreOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationUseCase_RestoreOrganization_Call) RunAndReturn(run func(context.Context, string) (*model.OrganizationResponse, error)) *MockOrganizationUseCase_RestoreOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrganization provides a mock function with given fields: ctx, id, request
func (_m *MockOrganizationUseCase) UpdateOrganization(ctx context.Context, id string, request *model.UpdateOrganizationRequest) (*model.OrganizationResponse, error) {
	ret := _m.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganization")
	}

	var r0 *model.OrganizationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.UpdateOrganizationRequest) (*model.OrganizationResponse, error)); ok {
		return rf(ctx, id, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.UpdateOrganizationRequest) *model.OrganizationResponse); ok {
		r0 = rf(ctx, id, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrganizationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.UpdateOrganizationRequest) error); ok {
		r1 = rf(ctx, id, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationUseCase_UpdateOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrganization'
type MockOrganizationUseCase_UpdateOrganization_Call struct {
	*mock.Call
}

// UpdateOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - request *model.UpdateOrganizationRequest
func (_e *MockOrganizationUseCase_Expecter) UpdateOrganization(ctx interface{}, id interface{}, request interface{}) *MockOrganizationUseCase_UpdateOrganization_Call {
	return &MockOrganizationUseCase_UpdateOrganization_Call{Call: _e.mock.On("UpdateOrganization", ctx, id, request)}
}

func (_c *MockOrganizationUseCase_UpdateOrganization_Call) Run(run func(ctx context.Context, id string, request *model.UpdateOrganizationRequest)) *MockOrganizationUseCase_UpdateOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.UpdateOrganizationRequest))
	})
	return _c
}

func (_c *MockOrganizationUseCase_UpdateOrganization_Call) Return(_a0 *model.OrganizationResponse, _a1 error) *MockOrganizationUseCase_UpdateOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationUseCase_UpdateOrganization_Call) RunAndReturn(run func(context.Context, string, *model.UpdateOrganizationRequest) (*model.OrganizationResponse, error)) *MockOrganizationUseCase_UpdateOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrganizationUseCase creates a new instance of MockOrganizationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationUseCase {
	mock := &MockOrganizationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
