// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIOrganizationReader is an autogenerated mock type for the IOrganizationReader type
type MockIOrganizationReader struct {
	mock.Mock
}

type MockIOrganizationReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOrganizationReader) EXPECT() *MockIOrganizationReader_Expecter {
	return &MockIOrganizationReader_Expecter{mock: &_m.Mock}
}

// GetMemberRole provides a mock function with given fields: ctx, orgID, userID
func (_m *MockIOrganizationReader) GetMemberRole(ctx context.Context, orgID string, userID string) (string, error) {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberRole")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, orgID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrganizationReader_GetMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberRole'
type MockIOrganizationReader_GetMemberRole_Call struct {
	*mock.Call
}

// GetMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockIOrganizationReader_Expecter) GetMemberRole(ctx interface{}, orgID interface{}, userID interface{}) *MockIOrganizationReader_GetMemberRole_Call {
	return &MockIOrganizationReader_GetMemberRole_Call{Call: _e.mock.On("GetMemberRole", ctx, orgID, userID)}
}

func (_c *MockIOrganizationReader_GetMemberRole_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockIOrganizationReader_GetMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIOrganizationReader_GetMemberRole_Call) Return(_a0 string, _a1 error) *MockIOrganizationReader_GetMemberRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrganizationReader_GetMemberRole_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockIOrganizationReader_GetMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateMembershipCache provides a mock function with given fields: ctx, orgID, userID
func (_m *MockIOrganizationReader) InvalidateMembershipCache(ctx context.Context, orgID string, userID string) error {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateMembershipCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOrganizationReader_InvalidateMembershipCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateMembershipCache'
type MockIOrganizationReader_InvalidateMembershipCache_Call struct {
	*mock.Call
}

// InvalidateMembershipCache is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockIOrganizationReader_Expecter) InvalidateMembershipCache(ctx interface{}, orgID interface{}, userID interface{}) *MockIOrganizationReader_InvalidateMembershipCache_Call {
	return &MockIOrganizationReader_InvalidateMembershipCache_Call{Call: _e.mock.On("InvalidateMembershipCache", ctx, orgID, userID)}
}

func (_c *MockIOrganizationReader_InvalidateMembershipCache_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockIOrganizationReader_InvalidateMembershipCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIOrganizationReader_InvalidateMembershipCache_Call) Return(_a0 error) *MockIOrganizationReader_InvalidateMembershipCache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOrganizationReader_InvalidateMembershipCache_Call) RunAndReturn(run func(context.Context, string, string) error) *MockIOrganizationReader_InvalidateMembershipCache_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateOrganizationCache provides a mock function with given fields: ctx, orgID
func (_m *MockIOrganizationReader) InvalidateOrganizationCache(ctx context.Context, orgID string) error {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateOrganizationCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOrganizationReader_InvalidateOrganizationCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateOrganizationCache'
type MockIOrganizationReader_InvalidateOrganizationCache_Call struct {
	*mock.Call
}

// InvalidateOrganizationCache is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockIOrganizationReader_Expecter) InvalidateOrganizationCache(ctx interface{}, orgID interface{}) *MockIOrganizationReader_InvalidateOrganizationCache_Call {
	return &MockIOrganizationReader_InvalidateOrganizationCache_Call{Call: _e.mock.On("InvalidateOrganizationCache", ctx, orgID)}
}

func (_c *MockIOrganizationReader_InvalidateOrganizationCache_Call) Run(run func(ctx context.Context, orgID string)) *MockIOrganizationReader_InvalidateOrganizationCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIOrganizationReader_InvalidateOrganizationCache_Call) Return(_a0 error) *MockIOrganizationReader_InvalidateOrganizationCache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOrganizationReader_InvalidateOrganizationCache_Call) RunAndReturn(run func(context.Context, string) error) *MockIOrganizationReader_InvalidateOrganizationCache_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateMembership provides a mock function with given fields: ctx, orgID, userID
func (_m *MockIOrganizationReader) ValidateMembership(ctx context.Context, orgID string, userID string) (bool, error) {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateMembership")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, orgID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOrganizationReader_ValidateMembership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateMembership'
type MockIOrganizationReader_ValidateMembership_Call struct {
	*mock.Call
}

// ValidateMembership is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockIOrganizationReader_Expecter) ValidateMembership(ctx interface{}, orgID interface{}, userID interface{}) *MockIOrganizationReader_ValidateMembership_Call {
	return &MockIOrganizationReader_ValidateMembership_Call{Call: _e.mock.On("ValidateMembership", ctx, orgID, userID)}
}

func (_c *MockIOrganizationReader_ValidateMembership_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockIOrganizationReader_ValidateMembership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIOrganizationReader_ValidateMembership_Call) Return(_a0 bool, _a1 error) *MockIOrganizationReader_ValidateMembership_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOrganizationReader_ValidateMembership_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockIOrganizationReader_ValidateMembership_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIOrganizationReader creates a new instance of MockIOrganizationReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOrganizationReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOrganizationReader {
	mock := &MockIOrganizationReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
