// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/organization/model"
	mock "github.com/stretchr/testify/mock"
)

// MockOrganizationMemberUseCase is an autogenerated mock type for the OrganizationMemberUseCase type
type MockOrganizationMemberUseCase struct {
	mock.Mock
}

type MockOrganizationMemberUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationMemberUseCase) EXPECT() *MockOrganizationMemberUseCase_Expecter {
	return &MockOrganizationMemberUseCase_Expecter{mock: &_m.Mock}
}

// AcceptInvitation provides a mock function with given fields: ctx, request
func (_m *MockOrganizationMemberUseCase) AcceptInvitation(ctx context.Context, request *model.AcceptInvitationRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.AcceptInvitationRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrganizationMemberUseCase_AcceptInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptInvitation'
type MockOrganizationMemberUseCase_AcceptInvitation_Call struct {
	*mock.Call
}

// AcceptInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - request *model.AcceptInvitationRequest
func (_e *MockOrganizationMemberUseCase_Expecter) AcceptInvitation(ctx interface{}, request interface{}) *MockOrganizationMemberUseCase_AcceptInvitation_Call {
	return &MockOrganizationMemberUseCase_AcceptInvitation_Call{Call: _e.mock.On("AcceptInvitation", ctx, request)}
}

func (_c *MockOrganizationMemberUseCase_AcceptInvitation_Call) Run(run func(ctx context.Context, request *model.AcceptInvitationRequest)) *MockOrganizationMemberUseCase_AcceptInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.AcceptInvitationRequest))
	})
	return _c
}

func (_c *MockOrganizationMemberUseCase_AcceptInvitation_Call) Return(_a0 error) *MockOrganizationMemberUseCase_AcceptInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrganizationMemberUseCase_AcceptInvitation_Call) RunAndReturn(run func(context.Context, *model.AcceptInvitationRequest) error) *MockOrganizationMemberUseCase_AcceptInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembers provides a mock function with given fields: ctx, orgID
func (_m *MockOrganizationMemberUseCase) GetMembers(ctx context.Context, orgID string) ([]model.MemberResponse, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []model.MemberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.MemberResponse, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.MemberResponse); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MemberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationMemberUseCase_GetMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembers'
type MockOrganizationMemberUseCase_GetMembers_Call struct {
	*mock.Call
}

// GetMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockOrganizationMemberUseCase_Expecter) GetMembers(ctx interface{}, orgID interface{}) *MockOrganizationMemberUseCase_GetMembers_Call {
	return &MockOrganizationMemberUseCase_GetMembers_Call{Call: _e.mock.On("GetMembers", ctx, orgID)}
}

func (_c *MockOrganizationMemberUseCase_GetMembers_Call) Run(run func(ctx context.Context, orgID string)) *MockOrganizationMemberUseCase_GetMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrganizationMemberUseCase_GetMembers_Call) Return(_a0 []model.MemberResponse, _a1 error) *MockOrganizationMemberUseCase_GetMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationMemberUseCase_GetMembers_Call) RunAndReturn(run func(context.Context, string) ([]model.MemberResponse, error)) *MockOrganizationMemberUseCase_GetMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresence provides a mock function with given fields: ctx, orgID
func (_m *MockOrganizationMemberUseCase) GetPresence(ctx context.Context, orgID string) ([]interface{}, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetPresence")
	}

	var r0 []interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]interface{}, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []interface{}); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationMemberUseCase_GetPresence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresence'
type MockOrganizationMemberUseCase_GetPresence_Call struct {
	*mock.Call
}

// GetPresence is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockOrganizationMemberUseCase_Expecter) GetPresence(ctx interface{}, orgID interface{}) *MockOrganizationMemberUseCase_GetPresence_Call {
	return &MockOrganizationMemberUseCase_GetPresence_Call{Call: _e.mock.On("GetPresence", ctx, orgID)}
}

func (_c *MockOrganizationMemberUseCase_GetPresence_Call) Run(run func(ctx context.Context, orgID string)) *MockOrganizationMemberUseCase_GetPresence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrganizationMemberUseCase_GetPresence_Call) Return(_a0 []interface{}, _a1 error) *MockOrganizationMemberUseCase_GetPresence_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationMemberUseCase_GetPresence_Call) RunAndReturn(run func(context.Context, string) ([]interface{}, error)) *MockOrganizationMemberUseCase_GetPresence_Call {
	_c.Call.Return(run)
	return _c
}

// InviteMember provides a mock function with given fields: ctx, orgID, request
func (_m *MockOrganizationMemberUseCase) InviteMember(ctx context.Context, orgID string, request *model.InviteMemberRequest) (*model.MemberResponse, error) {
	ret := _m.Called(ctx, orgID, request)

	if len(ret) == 0 {
		panic("no return value specified for InviteMember")
	}

	var r0 *model.MemberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.InviteMemberRequest) (*model.MemberResponse, error)); ok {
		return rf(ctx, orgID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.InviteMemberRequest) *model.MemberResponse); ok {
		r0 = rf(ctx, orgID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MemberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.InviteMemberRequest) error); ok {
		r1 = rf(ctx, orgID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationMemberUseCase_InviteMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InviteMember'
type MockOrganizationMemberUseCase_InviteMember_Call struct {
	*mock.Call
}

// InviteMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - request *model.InviteMemberRequest
func (_e *MockOrganizationMemberUseCase_Expecter) InviteMember(ctx interface{}, orgID interface{}, request interface{}) *MockOrganizationMemberUseCase_InviteMember_Call {
	return &MockOrganizationMemberUseCase_InviteMember_Call{Call: _e.mock.On("InviteMember", ctx, orgID, request)}
}

func (_c *MockOrganizationMemberUseCase_InviteMember_Call) Run(run func(ctx context.Context, orgID string, request *model.InviteMemberRequest)) *MockOrganizationMemberUseCase_InviteMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*model.InviteMemberRequest))
	})
	return _c
}

func (_c *MockOrganizationMemberUseCase_InviteMember_Call) Return(_a0 *model.MemberResponse, _a1 error) *MockOrganizationMemberUseCase_InviteMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationMemberUseCase_InviteMember_Call) RunAndReturn(run func(context.Context, string, *model.InviteMemberRequest) (*model.MemberResponse, error)) *MockOrganizationMemberUseCase_InviteMember_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, orgID, userID
func (_m *MockOrganizationMemberUseCase) RemoveMember(ctx context.Context, orgID string, userID string) error {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrganizationMemberUseCase_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockOrganizationMemberUseCase_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockOrganizationMemberUseCase_Expecter) RemoveMember(ctx interface{}, orgID interface{}, userID interface{}) *MockOrganizationMemberUseCase_RemoveMember_Call {
	return &MockOrganizationMemberUseCase_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, orgID, userID)}
}

func (_c *MockOrganizationMemberUseCase_RemoveMember_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockOrganizationMemberUseCase_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOrganizationMemberUseCase_RemoveMember_Call) Return(_a0 error) *MockOrganizationMemberUseCase_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrganizationMemberUseCase_RemoveMember_Call) RunAndReturn(run func(context.Context, string, string) error) *MockOrganizationMemberUseCase_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMember provides a mock function with given fields: ctx, orgID, userID, request
func (_m *MockOrganizationMemberUseCase) UpdateMember(ctx context.Context, orgID string, userID string, request *model.UpdateMemberRequest) (*model.MemberResponse, error) {
	ret := _m.Called(ctx, orgID, userID, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMember")
	}

	var r0 *model.MemberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.UpdateMemberRequest) (*model.MemberResponse, error)); ok {
		return rf(ctx, orgID, userID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.UpdateMemberRequest) *model.MemberResponse); ok {
		r0 = rf(ctx, orgID, userID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MemberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *model.UpdateMemberRequest) error); ok {
		r1 = rf(ctx, orgID, userID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationMemberUseCase_UpdateMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMember'
type MockOrganizationMemberUseCase_UpdateMember_Call struct {
	*mock.Call
}

// UpdateMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
//   - request *model.UpdateMemberRequest
func (_e *MockOrganizationMemberUseCase_Expecter) UpdateMember(ctx interface{}, orgID interface{}, userID interface{}, request interface{}) *MockOrganizationMemberUseCase_UpdateMember_Call {
	return &MockOrganizationMemberUseCase_UpdateMember_Call{Call: _e.mock.On("UpdateMember", ctx, orgID, userID, request)}
}

func (_c *MockOrganizationMemberUseCase_UpdateMember_Call) Run(run func(ctx context.Context, orgID string, userID string, request *model.UpdateMemberRequest)) *MockOrganizationMemberUseCase_UpdateMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*model.UpdateMemberRequest))
	})
	return _c
}

func (_c *MockOrganizationMemberUseCase_UpdateMember_Call) Return(_a0 *model.MemberResponse, _a1 error) *MockOrganizationMemberUseCase_UpdateMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationMemberUseCase_UpdateMember_Call) RunAndReturn(run func(context.Context, string, string, *model.UpdateMemberRequest) (*model.MemberResponse, error)) *MockOrganizationMemberUseCase_UpdateMember_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrganizationMemberUseCase creates a new instance of MockOrganizationMemberUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationMemberUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationMemberUseCase {
	mock := &MockOrganizationMemberUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
