// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/organization/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockInvitationRepository is an autogenerated mock type for the InvitationRepository type
type MockInvitationRepository struct {
	mock.Mock
}

type MockInvitationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInvitationRepository) EXPECT() *MockInvitationRepository_Expecter {
	return &MockInvitationRepository_Expecter{mock: &_m.Mock}
}

// CleanupExpired provides a mock function with given fields: ctx, now
func (_m *MockInvitationRepository) CleanupExpired(ctx context.Context, now int64) error {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, now)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInvitationRepository_CleanupExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupExpired'
type MockInvitationRepository_CleanupExpired_Call struct {
	*mock.Call
}

// CleanupExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - now int64
func (_e *MockInvitationRepository_Expecter) CleanupExpired(ctx interface{}, now interface{}) *MockInvitationRepository_CleanupExpired_Call {
	return &MockInvitationRepository_CleanupExpired_Call{Call: _e.mock.On("CleanupExpired", ctx, now)}
}

func (_c *MockInvitationRepository_CleanupExpired_Call) Run(run func(ctx context.Context, now int64)) *MockInvitationRepository_CleanupExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockInvitationRepository_CleanupExpired_Call) Return(_a0 error) *MockInvitationRepository_CleanupExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInvitationRepository_CleanupExpired_Call) RunAndReturn(run func(context.Context, int64) error) *MockInvitationRepository_CleanupExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, invitation
func (_m *MockInvitationRepository) Create(ctx context.Context, invitation *entity.InvitationToken) error {
	ret := _m.Called(ctx, invitation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.InvitationToken) error); ok {
		r0 = rf(ctx, invitation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInvitationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockInvitationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - invitation *entity.InvitationToken
func (_e *MockInvitationRepository_Expecter) Create(ctx interface{}, invitation interface{}) *MockInvitationRepository_Create_Call {
	return &MockInvitationRepository_Create_Call{Call: _e.mock.On("Create", ctx, invitation)}
}

func (_c *MockInvitationRepository_Create_Call) Run(run func(ctx context.Context, invitation *entity.InvitationToken)) *MockInvitationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.InvitationToken))
	})
	return _c
}

func (_c *MockInvitationRepository_Create_Call) Return(_a0 error) *MockInvitationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInvitationRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.InvitationToken) error) *MockInvitationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockInvitationRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInvitationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockInvitationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockInvitationRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockInvitationRepository_Delete_Call {
	return &MockInvitationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockInvitationRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockInvitationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInvitationRepository_Delete_Call) Return(_a0 error) *MockInvitationRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInvitationRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockInvitationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByEmailAndOrg provides a mock function with given fields: ctx, email, orgID
func (_m *MockInvitationRepository) DeleteByEmailAndOrg(ctx context.Context, email string, orgID string) error {
	ret := _m.Called(ctx, email, orgID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByEmailAndOrg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, orgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInvitationRepository_DeleteByEmailAndOrg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByEmailAndOrg'
type MockInvitationRepository_DeleteByEmailAndOrg_Call struct {
	*mock.Call
}

// DeleteByEmailAndOrg is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - orgID string
func (_e *MockInvitationRepository_Expecter) DeleteByEmailAndOrg(ctx interface{}, email interface{}, orgID interface{}) *MockInvitationRepository_DeleteByEmailAndOrg_Call {
	return &MockInvitationRepository_DeleteByEmailAndOrg_Call{Call: _e.mock.On("DeleteByEmailAndOrg", ctx, email, orgID)}
}

func (_c *MockInvitationRepository_DeleteByEmailAndOrg_Call) Run(run func(ctx context.Context, email string, orgID string)) *MockInvitationRepository_DeleteByEmailAndOrg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockInvitationRepository_DeleteByEmailAndOrg_Call) Return(_a0 error) *MockInvitationRepository_DeleteByEmailAndOrg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInvitationRepository_DeleteByEmailAndOrg_Call) RunAndReturn(run func(context.Context, string, string) error) *MockInvitationRepository_DeleteByEmailAndOrg_Call {
	_c.Call.Return(run)
	return _c
}

// FindByToken provides a mock function with given fields: ctx, token
func (_m *MockInvitationRepository) FindByToken(ctx context.Context, token string) (*entity.InvitationToken, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *entity.InvitationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.InvitationToken, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.InvitationToken); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.InvitationToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInvitationRepository_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type MockInvitationRepository_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockInvitationRepository_Expecter) FindByToken(ctx interface{}, token interface{}) *MockInvitationRepository_FindByToken_Call {
	return &MockInvitationRepository_FindByToken_Call{Call: _e.mock.On("FindByToken", ctx, token)}
}

func (_c *MockInvitationRepository_FindByToken_Call) Run(run func(ctx context.Context, token string)) *MockInvitationRepository_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInvitationRepository_FindByToken_Call) Return(_a0 *entity.InvitationToken, _a1 error) *MockInvitationRepository_FindByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInvitationRepository_FindByToken_Call) RunAndReturn(run func(context.Context, string) (*entity.InvitationToken, error)) *MockInvitationRepository_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInvitationRepository creates a new instance of MockInvitationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInvitationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInvitationRepository {
	mock := &MockInvitationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
