// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/organization/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockOrganizationMemberRepository is an autogenerated mock type for the OrganizationMemberRepository type
type MockOrganizationMemberRepository struct {
	mock.Mock
}

type MockOrganizationMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationMemberRepository) EXPECT() *MockOrganizationMemberRepository_Expecter {
	return &MockOrganizationMemberRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, member
func (_m *MockOrganizationMemberRepository) AddMember(ctx context.Context, member *entity.OrganizationMember) error {
	ret := _m.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.OrganizationMember) error); ok {
		r0 = rf(ctx, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrganizationMemberRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockOrganizationMemberRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - member *entity.OrganizationMember
func (_e *MockOrganizationMemberRepository_Expecter) AddMember(ctx interface{}, member interface{}) *MockOrganizationMemberRepository_AddMember_Call {
	return &MockOrganizationMemberRepository_AddMember_Call{Call: _e.mock.On("AddMember", ctx, member)}
}

func (_c *MockOrganizationMemberRepository_AddMember_Call) Run(run func(ctx context.Context, member *entity.OrganizationMember)) *MockOrganizationMemberRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.OrganizationMember))
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_AddMember_Call) Return(_a0 error) *MockOrganizationMemberRepository_AddMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrganizationMemberRepository_AddMember_Call) RunAndReturn(run func(context.Context, *entity.OrganizationMember) error) *MockOrganizationMemberRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// CheckMembership provides a mock function with given fields: ctx, orgID, userID
func (_m *MockOrganizationMemberRepository) CheckMembership(ctx context.Context, orgID string, userID string) (bool, error) {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CheckMembership")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, orgID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationMemberRepository_CheckMembership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckMembership'
type MockOrganizationMemberRepository_CheckMembership_Call struct {
	*mock.Call
}

// CheckMembership is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockOrganizationMemberRepository_Expecter) CheckMembership(ctx interface{}, orgID interface{}, userID interface{}) *MockOrganizationMemberRepository_CheckMembership_Call {
	return &MockOrganizationMemberRepository_CheckMembership_Call{Call: _e.mock.On("CheckMembership", ctx, orgID, userID)}
}

func (_c *MockOrganizationMemberRepository_CheckMembership_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockOrganizationMemberRepository_CheckMembership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_CheckMembership_Call) Return(_a0 bool, _a1 error) *MockOrganizationMemberRepository_CheckMembership_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationMemberRepository_CheckMembership_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockOrganizationMemberRepository_CheckMembership_Call {
	_c.Call.Return(run)
	return _c
}

// FindMemberForUpdate provides a mock function with given fields: ctx, orgID, userID
func (_m *MockOrganizationMemberRepository) FindMemberForUpdate(ctx context.Context, orgID string, userID string) (*entity.OrganizationMember, error) {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindMemberForUpdate")
	}

	var r0 *entity.OrganizationMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entity.OrganizationMember, error)); ok {
		return rf(ctx, orgID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.OrganizationMember); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OrganizationMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationMemberRepository_FindMemberForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMemberForUpdate'
type MockOrganizationMemberRepository_FindMemberForUpdate_Call struct {
	*mock.Call
}

// FindMemberForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockOrganizationMemberRepository_Expecter) FindMemberForUpdate(ctx interface{}, orgID interface{}, userID interface{}) *MockOrganizationMemberRepository_FindMemberForUpdate_Call {
	return &MockOrganizationMemberRepository_FindMemberForUpdate_Call{Call: _e.mock.On("FindMemberForUpdate", ctx, orgID, userID)}
}

func (_c *MockOrganizationMemberRepository_FindMemberForUpdate_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockOrganizationMemberRepository_FindMemberForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_FindMemberForUpdate_Call) Return(_a0 *entity.OrganizationMember, _a1 error) *MockOrganizationMemberRepository_FindMemberForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationMemberRepository_FindMemberForUpdate_Call) RunAndReturn(run func(context.Context, string, string) (*entity.OrganizationMember, error)) *MockOrganizationMemberRepository_FindMemberForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// FindMembers provides a mock function with given fields: ctx, orgID
func (_m *MockOrganizationMemberRepository) FindMembers(ctx context.Context, orgID string) ([]*entity.OrganizationMember, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for FindMembers")
	}

	var r0 []*entity.OrganizationMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entity.OrganizationMember, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entity.OrganizationMember); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.OrganizationMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationMemberRepository_FindMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMembers'
type MockOrganizationMemberRepository_FindMembers_Call struct {
	*mock.Call
}

// FindMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockOrganizationMemberRepository_Expecter) FindMembers(ctx interface{}, orgID interface{}) *MockOrganizationMemberRepository_FindMembers_Call {
	return &MockOrganizationMemberRepository_FindMembers_Call{Call: _e.mock.On("FindMembers", ctx, orgID)}
}

func (_c *MockOrganizationMemberRepository_FindMembers_Call) Run(run func(ctx context.Context, orgID string)) *MockOrganizationMemberRepository_FindMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_FindMembers_Call) Return(_a0 []*entity.OrganizationMember, _a1 error) *MockOrganizationMemberRepository_FindMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationMemberRepository_FindMembers_Call) RunAndReturn(run func(context.Context, string) ([]*entity.OrganizationMember, error)) *MockOrganizationMemberRepository_FindMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberRole provides a mock function with given fields: ctx, orgID, userID
func (_m *MockOrganizationMemberRepository) GetMemberRole(ctx context.Context, orgID string, userID string) (string, error) {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberRole")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, orgID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationMemberRepository_GetMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberRole'
type MockOrganizationMemberRepository_GetMemberRole_Call struct {
	*mock.Call
}

// GetMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockOrganizationMemberRepository_Expecter) GetMemberRole(ctx interface{}, orgID interface{}, userID interface{}) *MockOrganizationMemberRepository_GetMemberRole_Call {
	return &MockOrganizationMemberRepository_GetMemberRole_Call{Call: _e.mock.On("GetMemberRole", ctx, orgID, userID)}
}

func (_c *MockOrganizationMemberRepository_GetMemberRole_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockOrganizationMemberRepository_GetMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_GetMemberRole_Call) Return(_a0 string, _a1 error) *MockOrganizationMemberRepository_GetMemberRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationMemberRepository_GetMemberRole_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockOrganizationMemberRepository_GetMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberRoleName provides a mock function with given fields: ctx, orgID, userID
func (_m *MockOrganizationMemberRepository) GetMemberRoleName(ctx context.Context, orgID string, userID string) (string, error) {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberRoleName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, orgID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationMemberRepository_GetMemberRoleName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberRoleName'
type MockOrganizationMemberRepository_GetMemberRoleName_Call struct {
	*mock.Call
}

// GetMemberRoleName is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockOrganizationMemberRepository_Expecter) GetMemberRoleName(ctx interface{}, orgID interface{}, userID interface{}) *MockOrganizationMemberRepository_GetMemberRoleName_Call {
	return &MockOrganizationMemberRepository_GetMemberRoleName_Call{Call: _e.mock.On("GetMemberRoleName", ctx, orgID, userID)}
}

func (_c *MockOrganizationMemberRepository_GetMemberRoleName_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockOrganizationMemberRepository_GetMemberRoleName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_GetMemberRoleName_Call) Return(_a0 string, _a1 error) *MockOrganizationMemberRepository_GetMemberRoleName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationMemberRepository_GetMemberRoleName_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockOrganizationMemberRepository_GetMemberRoleName_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberStatus provides a mock function with given fields: ctx, orgID, userID
func (_m *MockOrganizationMemberRepository) GetMemberStatus(ctx context.Context, orgID string, userID string) (string, error) {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberStatus")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, orgID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, orgID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrganizationMemberRepository_GetMemberStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberStatus'
type MockOrganizationMemberRepository_GetMemberStatus_Call struct {
	*mock.Call
}

// GetMemberStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockOrganizationMemberRepository_Expecter) GetMemberStatus(ctx interface{}, orgID interface{}, userID interface{}) *MockOrganizationMemberRepository_GetMemberStatus_Call {
	return &MockOrganizationMemberRepository_GetMemberStatus_Call{Call: _e.mock.On("GetMemberStatus", ctx, orgID, userID)}
}

func (_c *MockOrganizationMemberRepository_GetMemberStatus_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockOrganizationMemberRepository_GetMemberStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_GetMemberStatus_Call) Return(_a0 string, _a1 error) *MockOrganizationMemberRepository_GetMemberStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrganizationMemberRepository_GetMemberStatus_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockOrganizationMemberRepository_GetMemberStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, orgID, userID
func (_m *MockOrganizationMemberRepository) RemoveMember(ctx context.Context, orgID string, userID string) error {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrganizationMemberRepository_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockOrganizationMemberRepository_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockOrganizationMemberRepository_Expecter) RemoveMember(ctx interface{}, orgID interface{}, userID interface{}) *MockOrganizationMemberRepository_RemoveMember_Call {
	return &MockOrganizationMemberRepository_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, orgID, userID)}
}

func (_c *MockOrganizationMemberRepository_RemoveMember_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockOrganizationMemberRepository_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_RemoveMember_Call) Return(_a0 error) *MockOrganizationMemberRepository_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrganizationMemberRepository_RemoveMember_Call) RunAndReturn(run func(context.Context, string, string) error) *MockOrganizationMemberRepository_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberRole provides a mock function with given fields: ctx, orgID, userID, roleID
func (_m *MockOrganizationMemberRepository) UpdateMemberRole(ctx context.Context, orgID string, userID string, roleID string) error {
	ret := _m.Called(ctx, orgID, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, orgID, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrganizationMemberRepository_UpdateMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberRole'
type MockOrganizationMemberRepository_UpdateMemberRole_Call struct {
	*mock.Call
}

// UpdateMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
//   - roleID string
func (_e *MockOrganizationMemberRepository_Expecter) UpdateMemberRole(ctx interface{}, orgID interface{}, userID interface{}, roleID interface{}) *MockOrganizationMemberRepository_UpdateMemberRole_Call {
	return &MockOrganizationMemberRepository_UpdateMemberRole_Call{Call: _e.mock.On("UpdateMemberRole", ctx, orgID, userID, roleID)}
}

func (_c *MockOrganizationMemberRepository_UpdateMemberRole_Call) Run(run func(ctx context.Context, orgID string, userID string, roleID string)) *MockOrganizationMemberRepository_UpdateMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_UpdateMemberRole_Call) Return(_a0 error) *MockOrganizationMemberRepository_UpdateMemberRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrganizationMemberRepository_UpdateMemberRole_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockOrganizationMemberRepository_UpdateMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberStatus provides a mock function with given fields: ctx, orgID, userID, status
func (_m *MockOrganizationMemberRepository) UpdateMemberStatus(ctx context.Context, orgID string, userID string, status string) error {
	ret := _m.Called(ctx, orgID, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, orgID, userID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrganizationMemberRepository_UpdateMemberStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberStatus'
type MockOrganizationMemberRepository_UpdateMemberStatus_Call struct {
	*mock.Call
}

// UpdateMemberStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
//   - status string
func (_e *MockOrganizationMemberRepository_Expecter) UpdateMemberStatus(ctx interface{}, orgID interface{}, userID interface{}, status interface{}) *MockOrganizationMemberRepository_UpdateMemberStatus_Call {
	return &MockOrganizationMemberRepository_UpdateMemberStatus_Call{Call: _e.mock.On("UpdateMemberStatus", ctx, orgID, userID, status)}
}

func (_c *MockOrganizationMemberRepository_UpdateMemberStatus_Call) Run(run func(ctx context.Context, orgID string, userID string, status string)) *MockOrganizationMemberRepository_UpdateMemberStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockOrganizationMemberRepository_UpdateMemberStatus_Call) Return(_a0 error) *MockOrganizationMemberRepository_UpdateMemberStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrganizationMemberRepository_UpdateMemberStatus_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockOrganizationMemberRepository_UpdateMemberStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrganizationMemberRepository creates a new instance of MockOrganizationMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationMemberRepository {
	mock := &MockOrganizationMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
