// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function with given fields: ctx, filename
func (_m *MockProvider) DeleteFile(ctx context.Context, filename string) error {
	ret := _m.Called(ctx, filename)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, filename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProvider_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockProvider_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
func (_e *MockProvider_Expecter) DeleteFile(ctx interface{}, filename interface{}) *MockProvider_DeleteFile_Call {
	return &MockProvider_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, filename)}
}

func (_c *MockProvider_DeleteFile_Call) Run(run func(ctx context.Context, filename string)) *MockProvider_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProvider_DeleteFile_Call) Return(_a0 error) *MockProvider_DeleteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProvider_DeleteFile_Call) RunAndReturn(run func(context.Context, string) error) *MockProvider_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileUrl provides a mock function with given fields: ctx, filename
func (_m *MockProvider) GetFileUrl(ctx context.Context, filename string) (string, error) {
	ret := _m.Called(ctx, filename)

	if len(ret) == 0 {
		panic("no return value specified for GetFileUrl")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, filename)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, filename)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_GetFileUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileUrl'
type MockProvider_GetFileUrl_Call struct {
	*mock.Call
}

// GetFileUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
func (_e *MockProvider_Expecter) GetFileUrl(ctx interface{}, filename interface{}) *MockProvider_GetFileUrl_Call {
	return &MockProvider_GetFileUrl_Call{Call: _e.mock.On("GetFileUrl", ctx, filename)}
}

func (_c *MockProvider_GetFileUrl_Call) Run(run func(ctx context.Context, filename string)) *MockProvider_GetFileUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProvider_GetFileUrl_Call) Return(_a0 string, _a1 error) *MockProvider_GetFileUrl_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_GetFileUrl_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockProvider_GetFileUrl_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function with given fields: ctx, file, filename, contentType
func (_m *MockProvider) UploadFile(ctx context.Context, file io.Reader, filename string, contentType string) (string, error) {
	ret := _m.Called(ctx, file, filename, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) (string, error)); ok {
		return rf(ctx, file, filename, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, string, string) string); ok {
		r0 = rf(ctx, file, filename, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader, string, string) error); ok {
		r1 = rf(ctx, file, filename, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProvider_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type MockProvider_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - file io.Reader
//   - filename string
//   - contentType string
func (_e *MockProvider_Expecter) UploadFile(ctx interface{}, file interface{}, filename interface{}, contentType interface{}) *MockProvider_UploadFile_Call {
	return &MockProvider_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, file, filename, contentType)}
}

func (_c *MockProvider_UploadFile_Call) Run(run func(ctx context.Context, file io.Reader, filename string, contentType string)) *MockProvider_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockProvider_UploadFile_Call) Return(_a0 string, _a1 error) *MockProvider_UploadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProvider_UploadFile_Call) RunAndReturn(run func(context.Context, io.Reader, string, string) (string, error)) *MockProvider_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
