// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IPermissionUseCase is an autogenerated mock type for the IPermissionUseCase type
type IPermissionUseCase struct {
	mock.Mock
}

// AssignRoleToUser provides a mock function with given fields: ctx, userID, role
func (_m *IPermissionUseCase) AssignRoleToUser(ctx context.Context, userID string, role string) error {
	ret := _m.Called(ctx, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AssignRoleToUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllPermissions provides a mock function with given fields:
func (_m *IPermissionUseCase) GetAllPermissions() ([][]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllPermissions")
	}

	var r0 [][]string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([][]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() [][]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPermissionsForRole provides a mock function with given fields: role
func (_m *IPermissionUseCase) GetPermissionsForRole(role string) ([][]string, error) {
	ret := _m.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionsForRole")
	}

	var r0 [][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([][]string, error)); ok {
		return rf(role)
	}
	if rf, ok := ret.Get(0).(func(string) [][]string); ok {
		r0 = rf(role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GrantPermissionToRole provides a mock function with given fields: ctx, role, path, method
func (_m *IPermissionUseCase) GrantPermissionToRole(ctx context.Context, role string, path string, method string) error {
	ret := _m.Called(ctx, role, path, method)

	if len(ret) == 0 {
		panic("no return value specified for GrantPermissionToRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, role, path, method)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokePermissionFromRole provides a mock function with given fields: ctx, role, path, method
func (_m *IPermissionUseCase) RevokePermissionFromRole(ctx context.Context, role string, path string, method string) error {
	ret := _m.Called(ctx, role, path, method)

	if len(ret) == 0 {
		panic("no return value specified for RevokePermissionFromRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, role, path, method)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePermission provides a mock function with given fields: oldPerm, newPerm
func (_m *IPermissionUseCase) UpdatePermission(oldPerm []string, newPerm []string) (bool, error) {
	ret := _m.Called(oldPerm, newPerm)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePermission")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func([]string, []string) (bool, error)); ok {
		return rf(oldPerm, newPerm)
	}
	if rf, ok := ret.Get(0).(func([]string, []string) bool); ok {
		r0 = rf(oldPerm, newPerm)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func([]string, []string) error); ok {
		r1 = rf(oldPerm, newPerm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIPermissionUseCase creates a new instance of IPermissionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPermissionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPermissionUseCase {
	mock := &IPermissionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
