// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/permission/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockIEnforcer is an autogenerated mock type for the IEnforcer type
type MockIEnforcer struct {
	mock.Mock
}

type MockIEnforcer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIEnforcer) EXPECT() *MockIEnforcer_Expecter {
	return &MockIEnforcer_Expecter{mock: &_m.Mock}
}

// AddGroupingPolicy provides a mock function with given fields: params
func (_m *MockIEnforcer) AddGroupingPolicy(params ...interface{}) (bool, error) {
	var _ca []interface{}
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddGroupingPolicy")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(...interface{}) (bool, error)); ok {
		return rf(params...)
	}
	if rf, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = rf(params...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(params...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_AddGroupingPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGroupingPolicy'
type MockIEnforcer_AddGroupingPolicy_Call struct {
	*mock.Call
}

// AddGroupingPolicy is a helper method to define mock.On call
//   - params ...interface{}
func (_e *MockIEnforcer_Expecter) AddGroupingPolicy(params ...interface{}) *MockIEnforcer_AddGroupingPolicy_Call {
	return &MockIEnforcer_AddGroupingPolicy_Call{Call: _e.mock.On("AddGroupingPolicy",
		append([]interface{}{}, params...)...)}
}

func (_c *MockIEnforcer_AddGroupingPolicy_Call) Run(run func(params ...interface{})) *MockIEnforcer_AddGroupingPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockIEnforcer_AddGroupingPolicy_Call) Return(_a0 bool, _a1 error) *MockIEnforcer_AddGroupingPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_AddGroupingPolicy_Call) RunAndReturn(run func(...interface{}) (bool, error)) *MockIEnforcer_AddGroupingPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// AddPolicy provides a mock function with given fields: params
func (_m *MockIEnforcer) AddPolicy(params ...interface{}) (bool, error) {
	var _ca []interface{}
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AddPolicy")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(...interface{}) (bool, error)); ok {
		return rf(params...)
	}
	if rf, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = rf(params...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(params...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_AddPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPolicy'
type MockIEnforcer_AddPolicy_Call struct {
	*mock.Call
}

// AddPolicy is a helper method to define mock.On call
//   - params ...interface{}
func (_e *MockIEnforcer_Expecter) AddPolicy(params ...interface{}) *MockIEnforcer_AddPolicy_Call {
	return &MockIEnforcer_AddPolicy_Call{Call: _e.mock.On("AddPolicy",
		append([]interface{}{}, params...)...)}
}

func (_c *MockIEnforcer_AddPolicy_Call) Run(run func(params ...interface{})) *MockIEnforcer_AddPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockIEnforcer_AddPolicy_Call) Return(_a0 bool, _a1 error) *MockIEnforcer_AddPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_AddPolicy_Call) RunAndReturn(run func(...interface{}) (bool, error)) *MockIEnforcer_AddPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRole provides a mock function with given fields: role
func (_m *MockIEnforcer) DeleteRole(role string) (bool, error) {
	ret := _m.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRole")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(role)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(role)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_DeleteRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRole'
type MockIEnforcer_DeleteRole_Call struct {
	*mock.Call
}

// DeleteRole is a helper method to define mock.On call
//   - role string
func (_e *MockIEnforcer_Expecter) DeleteRole(role interface{}) *MockIEnforcer_DeleteRole_Call {
	return &MockIEnforcer_DeleteRole_Call{Call: _e.mock.On("DeleteRole", role)}
}

func (_c *MockIEnforcer_DeleteRole_Call) Run(run func(role string)) *MockIEnforcer_DeleteRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIEnforcer_DeleteRole_Call) Return(_a0 bool, _a1 error) *MockIEnforcer_DeleteRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_DeleteRole_Call) RunAndReturn(run func(string) (bool, error)) *MockIEnforcer_DeleteRole_Call {
	_c.Call.Return(run)
	return _c
}

// Enforce provides a mock function with given fields: params
func (_m *MockIEnforcer) Enforce(params ...interface{}) (bool, error) {
	var _ca []interface{}
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Enforce")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(...interface{}) (bool, error)); ok {
		return rf(params...)
	}
	if rf, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = rf(params...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(params...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_Enforce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enforce'
type MockIEnforcer_Enforce_Call struct {
	*mock.Call
}

// Enforce is a helper method to define mock.On call
//   - params ...interface{}
func (_e *MockIEnforcer_Expecter) Enforce(params ...interface{}) *MockIEnforcer_Enforce_Call {
	return &MockIEnforcer_Enforce_Call{Call: _e.mock.On("Enforce",
		append([]interface{}{}, params...)...)}
}

func (_c *MockIEnforcer_Enforce_Call) Run(run func(params ...interface{})) *MockIEnforcer_Enforce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockIEnforcer_Enforce_Call) Return(_a0 bool, _a1 error) *MockIEnforcer_Enforce_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_Enforce_Call) RunAndReturn(run func(...interface{}) (bool, error)) *MockIEnforcer_Enforce_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilteredPolicy provides a mock function with given fields: fieldIndex, fieldValues
func (_m *MockIEnforcer) GetFilteredPolicy(fieldIndex int, fieldValues ...string) ([][]string, error) {
	_va := make([]interface{}, len(fieldValues))
	for _i := range fieldValues {
		_va[_i] = fieldValues[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, fieldIndex)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetFilteredPolicy")
	}

	var r0 [][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(int, ...string) ([][]string, error)); ok {
		return rf(fieldIndex, fieldValues...)
	}
	if rf, ok := ret.Get(0).(func(int, ...string) [][]string); ok {
		r0 = rf(fieldIndex, fieldValues...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(int, ...string) error); ok {
		r1 = rf(fieldIndex, fieldValues...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_GetFilteredPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilteredPolicy'
type MockIEnforcer_GetFilteredPolicy_Call struct {
	*mock.Call
}

// GetFilteredPolicy is a helper method to define mock.On call
//   - fieldIndex int
//   - fieldValues ...string
func (_e *MockIEnforcer_Expecter) GetFilteredPolicy(fieldIndex interface{}, fieldValues ...interface{}) *MockIEnforcer_GetFilteredPolicy_Call {
	return &MockIEnforcer_GetFilteredPolicy_Call{Call: _e.mock.On("GetFilteredPolicy",
		append([]interface{}{fieldIndex}, fieldValues...)...)}
}

func (_c *MockIEnforcer_GetFilteredPolicy_Call) Run(run func(fieldIndex int, fieldValues ...string)) *MockIEnforcer_GetFilteredPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(int), variadicArgs...)
	})
	return _c
}

func (_c *MockIEnforcer_GetFilteredPolicy_Call) Return(_a0 [][]string, _a1 error) *MockIEnforcer_GetFilteredPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_GetFilteredPolicy_Call) RunAndReturn(run func(int, ...string) ([][]string, error)) *MockIEnforcer_GetFilteredPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetPolicy provides a mock function with no fields
func (_m *MockIEnforcer) GetPolicy() ([][]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPolicy")
	}

	var r0 [][]string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([][]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() [][]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_GetPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPolicy'
type MockIEnforcer_GetPolicy_Call struct {
	*mock.Call
}

// GetPolicy is a helper method to define mock.On call
func (_e *MockIEnforcer_Expecter) GetPolicy() *MockIEnforcer_GetPolicy_Call {
	return &MockIEnforcer_GetPolicy_Call{Call: _e.mock.On("GetPolicy")}
}

func (_c *MockIEnforcer_GetPolicy_Call) Run(run func()) *MockIEnforcer_GetPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIEnforcer_GetPolicy_Call) Return(_a0 [][]string, _a1 error) *MockIEnforcer_GetPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_GetPolicy_Call) RunAndReturn(run func() ([][]string, error)) *MockIEnforcer_GetPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetRolesForUser provides a mock function with given fields: name, domain
func (_m *MockIEnforcer) GetRolesForUser(name string, domain ...string) ([]string, error) {
	_va := make([]interface{}, len(domain))
	for _i := range domain {
		_va[_i] = domain[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetRolesForUser")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...string) ([]string, error)); ok {
		return rf(name, domain...)
	}
	if rf, ok := ret.Get(0).(func(string, ...string) []string); ok {
		r0 = rf(name, domain...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = rf(name, domain...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_GetRolesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRolesForUser'
type MockIEnforcer_GetRolesForUser_Call struct {
	*mock.Call
}

// GetRolesForUser is a helper method to define mock.On call
//   - name string
//   - domain ...string
func (_e *MockIEnforcer_Expecter) GetRolesForUser(name interface{}, domain ...interface{}) *MockIEnforcer_GetRolesForUser_Call {
	return &MockIEnforcer_GetRolesForUser_Call{Call: _e.mock.On("GetRolesForUser",
		append([]interface{}{name}, domain...)...)}
}

func (_c *MockIEnforcer_GetRolesForUser_Call) Run(run func(name string, domain ...string)) *MockIEnforcer_GetRolesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIEnforcer_GetRolesForUser_Call) Return(_a0 []string, _a1 error) *MockIEnforcer_GetRolesForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_GetRolesForUser_Call) RunAndReturn(run func(string, ...string) ([]string, error)) *MockIEnforcer_GetRolesForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersForRole provides a mock function with given fields: name, domain
func (_m *MockIEnforcer) GetUsersForRole(name string, domain ...string) ([]string, error) {
	_va := make([]interface{}, len(domain))
	for _i := range domain {
		_va[_i] = domain[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersForRole")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...string) ([]string, error)); ok {
		return rf(name, domain...)
	}
	if rf, ok := ret.Get(0).(func(string, ...string) []string); ok {
		r0 = rf(name, domain...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = rf(name, domain...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_GetUsersForRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersForRole'
type MockIEnforcer_GetUsersForRole_Call struct {
	*mock.Call
}

// GetUsersForRole is a helper method to define mock.On call
//   - name string
//   - domain ...string
func (_e *MockIEnforcer_Expecter) GetUsersForRole(name interface{}, domain ...interface{}) *MockIEnforcer_GetUsersForRole_Call {
	return &MockIEnforcer_GetUsersForRole_Call{Call: _e.mock.On("GetUsersForRole",
		append([]interface{}{name}, domain...)...)}
}

func (_c *MockIEnforcer_GetUsersForRole_Call) Run(run func(name string, domain ...string)) *MockIEnforcer_GetUsersForRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockIEnforcer_GetUsersForRole_Call) Return(_a0 []string, _a1 error) *MockIEnforcer_GetUsersForRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_GetUsersForRole_Call) RunAndReturn(run func(string, ...string) ([]string, error)) *MockIEnforcer_GetUsersForRole_Call {
	_c.Call.Return(run)
	return _c
}

// HasGroupingPolicy provides a mock function with given fields: params
func (_m *MockIEnforcer) HasGroupingPolicy(params ...interface{}) (bool, error) {
	var _ca []interface{}
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HasGroupingPolicy")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(...interface{}) (bool, error)); ok {
		return rf(params...)
	}
	if rf, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = rf(params...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(params...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_HasGroupingPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasGroupingPolicy'
type MockIEnforcer_HasGroupingPolicy_Call struct {
	*mock.Call
}

// HasGroupingPolicy is a helper method to define mock.On call
//   - params ...interface{}
func (_e *MockIEnforcer_Expecter) HasGroupingPolicy(params ...interface{}) *MockIEnforcer_HasGroupingPolicy_Call {
	return &MockIEnforcer_HasGroupingPolicy_Call{Call: _e.mock.On("HasGroupingPolicy",
		append([]interface{}{}, params...)...)}
}

func (_c *MockIEnforcer_HasGroupingPolicy_Call) Run(run func(params ...interface{})) *MockIEnforcer_HasGroupingPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockIEnforcer_HasGroupingPolicy_Call) Return(_a0 bool, _a1 error) *MockIEnforcer_HasGroupingPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_HasGroupingPolicy_Call) RunAndReturn(run func(...interface{}) (bool, error)) *MockIEnforcer_HasGroupingPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// HasPolicy provides a mock function with given fields: params
func (_m *MockIEnforcer) HasPolicy(params ...interface{}) (bool, error) {
	var _ca []interface{}
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HasPolicy")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(...interface{}) (bool, error)); ok {
		return rf(params...)
	}
	if rf, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = rf(params...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(params...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_HasPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPolicy'
type MockIEnforcer_HasPolicy_Call struct {
	*mock.Call
}

// HasPolicy is a helper method to define mock.On call
//   - params ...interface{}
func (_e *MockIEnforcer_Expecter) HasPolicy(params ...interface{}) *MockIEnforcer_HasPolicy_Call {
	return &MockIEnforcer_HasPolicy_Call{Call: _e.mock.On("HasPolicy",
		append([]interface{}{}, params...)...)}
}

func (_c *MockIEnforcer_HasPolicy_Call) Run(run func(params ...interface{})) *MockIEnforcer_HasPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockIEnforcer_HasPolicy_Call) Return(_a0 bool, _a1 error) *MockIEnforcer_HasPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_HasPolicy_Call) RunAndReturn(run func(...interface{}) (bool, error)) *MockIEnforcer_HasPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// LoadPolicy provides a mock function with no fields
func (_m *MockIEnforcer) LoadPolicy() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadPolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIEnforcer_LoadPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadPolicy'
type MockIEnforcer_LoadPolicy_Call struct {
	*mock.Call
}

// LoadPolicy is a helper method to define mock.On call
func (_e *MockIEnforcer_Expecter) LoadPolicy() *MockIEnforcer_LoadPolicy_Call {
	return &MockIEnforcer_LoadPolicy_Call{Call: _e.mock.On("LoadPolicy")}
}

func (_c *MockIEnforcer_LoadPolicy_Call) Run(run func()) *MockIEnforcer_LoadPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIEnforcer_LoadPolicy_Call) Return(_a0 error) *MockIEnforcer_LoadPolicy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIEnforcer_LoadPolicy_Call) RunAndReturn(run func() error) *MockIEnforcer_LoadPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFilteredGroupingPolicy provides a mock function with given fields: fieldIndex, fieldValues
func (_m *MockIEnforcer) RemoveFilteredGroupingPolicy(fieldIndex int, fieldValues ...string) (bool, error) {
	_va := make([]interface{}, len(fieldValues))
	for _i := range fieldValues {
		_va[_i] = fieldValues[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, fieldIndex)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFilteredGroupingPolicy")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int, ...string) (bool, error)); ok {
		return rf(fieldIndex, fieldValues...)
	}
	if rf, ok := ret.Get(0).(func(int, ...string) bool); ok {
		r0 = rf(fieldIndex, fieldValues...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int, ...string) error); ok {
		r1 = rf(fieldIndex, fieldValues...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_RemoveFilteredGroupingPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFilteredGroupingPolicy'
type MockIEnforcer_RemoveFilteredGroupingPolicy_Call struct {
	*mock.Call
}

// RemoveFilteredGroupingPolicy is a helper method to define mock.On call
//   - fieldIndex int
//   - fieldValues ...string
func (_e *MockIEnforcer_Expecter) RemoveFilteredGroupingPolicy(fieldIndex interface{}, fieldValues ...interface{}) *MockIEnforcer_RemoveFilteredGroupingPolicy_Call {
	return &MockIEnforcer_RemoveFilteredGroupingPolicy_Call{Call: _e.mock.On("RemoveFilteredGroupingPolicy",
		append([]interface{}{fieldIndex}, fieldValues...)...)}
}

func (_c *MockIEnforcer_RemoveFilteredGroupingPolicy_Call) Run(run func(fieldIndex int, fieldValues ...string)) *MockIEnforcer_RemoveFilteredGroupingPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(int), variadicArgs...)
	})
	return _c
}

func (_c *MockIEnforcer_RemoveFilteredGroupingPolicy_Call) Return(_a0 bool, _a1 error) *MockIEnforcer_RemoveFilteredGroupingPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_RemoveFilteredGroupingPolicy_Call) RunAndReturn(run func(int, ...string) (bool, error)) *MockIEnforcer_RemoveFilteredGroupingPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFilteredPolicy provides a mock function with given fields: fieldIndex, fieldValues
func (_m *MockIEnforcer) RemoveFilteredPolicy(fieldIndex int, fieldValues ...string) (bool, error) {
	_va := make([]interface{}, len(fieldValues))
	for _i := range fieldValues {
		_va[_i] = fieldValues[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, fieldIndex)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFilteredPolicy")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int, ...string) (bool, error)); ok {
		return rf(fieldIndex, fieldValues...)
	}
	if rf, ok := ret.Get(0).(func(int, ...string) bool); ok {
		r0 = rf(fieldIndex, fieldValues...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int, ...string) error); ok {
		r1 = rf(fieldIndex, fieldValues...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_RemoveFilteredPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFilteredPolicy'
type MockIEnforcer_RemoveFilteredPolicy_Call struct {
	*mock.Call
}

// RemoveFilteredPolicy is a helper method to define mock.On call
//   - fieldIndex int
//   - fieldValues ...string
func (_e *MockIEnforcer_Expecter) RemoveFilteredPolicy(fieldIndex interface{}, fieldValues ...interface{}) *MockIEnforcer_RemoveFilteredPolicy_Call {
	return &MockIEnforcer_RemoveFilteredPolicy_Call{Call: _e.mock.On("RemoveFilteredPolicy",
		append([]interface{}{fieldIndex}, fieldValues...)...)}
}

func (_c *MockIEnforcer_RemoveFilteredPolicy_Call) Run(run func(fieldIndex int, fieldValues ...string)) *MockIEnforcer_RemoveFilteredPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(int), variadicArgs...)
	})
	return _c
}

func (_c *MockIEnforcer_RemoveFilteredPolicy_Call) Return(_a0 bool, _a1 error) *MockIEnforcer_RemoveFilteredPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_RemoveFilteredPolicy_Call) RunAndReturn(run func(int, ...string) (bool, error)) *MockIEnforcer_RemoveFilteredPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePolicy provides a mock function with given fields: params
func (_m *MockIEnforcer) RemovePolicy(params ...interface{}) (bool, error) {
	var _ca []interface{}
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RemovePolicy")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(...interface{}) (bool, error)); ok {
		return rf(params...)
	}
	if rf, ok := ret.Get(0).(func(...interface{}) bool); ok {
		r0 = rf(params...)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(params...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_RemovePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePolicy'
type MockIEnforcer_RemovePolicy_Call struct {
	*mock.Call
}

// RemovePolicy is a helper method to define mock.On call
//   - params ...interface{}
func (_e *MockIEnforcer_Expecter) RemovePolicy(params ...interface{}) *MockIEnforcer_RemovePolicy_Call {
	return &MockIEnforcer_RemovePolicy_Call{Call: _e.mock.On("RemovePolicy",
		append([]interface{}{}, params...)...)}
}

func (_c *MockIEnforcer_RemovePolicy_Call) Run(run func(params ...interface{})) *MockIEnforcer_RemovePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockIEnforcer_RemovePolicy_Call) Return(_a0 bool, _a1 error) *MockIEnforcer_RemovePolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_RemovePolicy_Call) RunAndReturn(run func(...interface{}) (bool, error)) *MockIEnforcer_RemovePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// SavePolicy provides a mock function with no fields
func (_m *MockIEnforcer) SavePolicy() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SavePolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIEnforcer_SavePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePolicy'
type MockIEnforcer_SavePolicy_Call struct {
	*mock.Call
}

// SavePolicy is a helper method to define mock.On call
func (_e *MockIEnforcer_Expecter) SavePolicy() *MockIEnforcer_SavePolicy_Call {
	return &MockIEnforcer_SavePolicy_Call{Call: _e.mock.On("SavePolicy")}
}

func (_c *MockIEnforcer_SavePolicy_Call) Run(run func()) *MockIEnforcer_SavePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIEnforcer_SavePolicy_Call) Return(_a0 error) *MockIEnforcer_SavePolicy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIEnforcer_SavePolicy_Call) RunAndReturn(run func() error) *MockIEnforcer_SavePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePolicy provides a mock function with given fields: oldRule, newRule
func (_m *MockIEnforcer) UpdatePolicy(oldRule []string, newRule []string) (bool, error) {
	ret := _m.Called(oldRule, newRule)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePolicy")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func([]string, []string) (bool, error)); ok {
		return rf(oldRule, newRule)
	}
	if rf, ok := ret.Get(0).(func([]string, []string) bool); ok {
		r0 = rf(oldRule, newRule)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func([]string, []string) error); ok {
		r1 = rf(oldRule, newRule)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIEnforcer_UpdatePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePolicy'
type MockIEnforcer_UpdatePolicy_Call struct {
	*mock.Call
}

// UpdatePolicy is a helper method to define mock.On call
//   - oldRule []string
//   - newRule []string
func (_e *MockIEnforcer_Expecter) UpdatePolicy(oldRule interface{}, newRule interface{}) *MockIEnforcer_UpdatePolicy_Call {
	return &MockIEnforcer_UpdatePolicy_Call{Call: _e.mock.On("UpdatePolicy", oldRule, newRule)}
}

func (_c *MockIEnforcer_UpdatePolicy_Call) Run(run func(oldRule []string, newRule []string)) *MockIEnforcer_UpdatePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string), args[1].([]string))
	})
	return _c
}

func (_c *MockIEnforcer_UpdatePolicy_Call) Return(_a0 bool, _a1 error) *MockIEnforcer_UpdatePolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIEnforcer_UpdatePolicy_Call) RunAndReturn(run func([]string, []string) (bool, error)) *MockIEnforcer_UpdatePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// WithContext provides a mock function with given fields: ctx
func (_m *MockIEnforcer) WithContext(ctx context.Context) usecase.IEnforcer {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WithContext")
	}

	var r0 usecase.IEnforcer
	if rf, ok := ret.Get(0).(func(context.Context) usecase.IEnforcer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(usecase.IEnforcer)
		}
	}

	return r0
}

// MockIEnforcer_WithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithContext'
type MockIEnforcer_WithContext_Call struct {
	*mock.Call
}

// WithContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIEnforcer_Expecter) WithContext(ctx interface{}) *MockIEnforcer_WithContext_Call {
	return &MockIEnforcer_WithContext_Call{Call: _e.mock.On("WithContext", ctx)}
}

func (_c *MockIEnforcer_WithContext_Call) Run(run func(ctx context.Context)) *MockIEnforcer_WithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIEnforcer_WithContext_Call) Return(_a0 usecase.IEnforcer) *MockIEnforcer_WithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIEnforcer_WithContext_Call) RunAndReturn(run func(context.Context) usecase.IEnforcer) *MockIEnforcer_WithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIEnforcer creates a new instance of MockIEnforcer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIEnforcer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIEnforcer {
	mock := &MockIEnforcer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
