// Code generated by mockery; DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/permission/model"
	mock "github.com/stretchr/testify/mock"
)

// MockIPermissionUseCase is an autogenerated mock type for the IPermissionUseCase type
type MockIPermissionUseCase struct {
	mock.Mock
}

// NewMockIPermissionUseCase creates a new instance of MockIPermissionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIPermissionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPermissionUseCase {
	mock := &MockIPermissionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AddParentRole provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) AddParentRole(ctx context.Context, childRole string, parentRole string, domain string) error {
	ret := _m.Called(ctx, childRole, parentRole, domain)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, childRole, parentRole, domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssignRoleToUser provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) AssignRoleToUser(ctx context.Context, userID string, role string, domain string) error {
	ret := _m.Called(ctx, userID, role, domain)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, role, domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BatchCheckPermission provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) BatchCheckPermission(ctx context.Context, userID string, items []model.PermissionCheckItem) (map[string]bool, error) {
	ret := _m.Called(ctx, userID, items)

	var r0 map[string]bool
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.PermissionCheckItem) map[string]bool); ok {
		r0 = rf(ctx, userID, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, []model.PermissionCheckItem) error); ok {
		r1 = rf(ctx, userID, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPermissions provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) GetAllPermissions(ctx context.Context) ([][]string, error) {
	ret := _m.Called(ctx)

	var r0 [][]string
	if rf, ok := ret.Get(0).(func(context.Context) [][]string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInheritanceTree provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) GetInheritanceTree(ctx context.Context) (*model.InheritanceTreeResponse, error) {
	ret := _m.Called(ctx)

	var r0 *model.InheritanceTreeResponse
	if rf, ok := ret.Get(0).(func(context.Context) *model.InheritanceTreeResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.InheritanceTreeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetParentRoles provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) GetParentRoles(ctx context.Context, role string, domain string) ([]string, error) {
	ret := _m.Called(ctx, role, domain)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, role, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, role, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPermissionsForRole provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) GetPermissionsForRole(ctx context.Context, role string) ([][]string, error) {
	ret := _m.Called(ctx, role)

	var r0 [][]string
	if rf, ok := ret.Get(0).(func(context.Context, string) [][]string); ok {
		r0 = rf(ctx, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetResourceAggregation provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) GetResourceAggregation(ctx context.Context) (*model.ResourceAggregationResponse, error) {
	ret := _m.Called(ctx)

	var r0 *model.ResourceAggregationResponse
	if rf, ok := ret.Get(0).(func(context.Context) *model.ResourceAggregationResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ResourceAggregationResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersForRole provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) GetUsersForRole(ctx context.Context, role string, domain string) ([]string, error) {
	ret := _m.Called(ctx, role, domain)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, role, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, role, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GrantPermissionToRole provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) GrantPermissionToRole(ctx context.Context, role string, path string, method string, domain string) error {
	ret := _m.Called(ctx, role, path, method, domain)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, role, path, method, domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveParentRole provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) RemoveParentRole(ctx context.Context, childRole string, parentRole string, domain string) error {
	ret := _m.Called(ctx, childRole, parentRole, domain)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, childRole, parentRole, domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokePermissionFromRole provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) RevokePermissionFromRole(ctx context.Context, role string, path string, method string, domain string) error {
	ret := _m.Called(ctx, role, path, method, domain)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, role, path, method, domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeRoleFromUser provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) RevokeRoleFromUser(ctx context.Context, userID string, role string, domain string) error {
	ret := _m.Called(ctx, userID, role, domain)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, role, domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePermission provides a mock function for the type IPermissionUseCase
func (_m *MockIPermissionUseCase) UpdatePermission(ctx context.Context, oldPermission []string, newPermission []string) (bool, error) {
	ret := _m.Called(ctx, oldPermission, newPermission)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string) bool); ok {
		r0 = rf(ctx, oldPermission, newPermission)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string, []string) error); ok {
		r1 = rf(ctx, oldPermission, newPermission)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
