// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/Roisfaozi/casbin-db/internal/modules/access/model"
	mock "github.com/stretchr/testify/mock"
)

// IAccessUseCase is an autogenerated mock type for the IAccessUseCase type
type IAccessUseCase struct {
	mock.Mock
}

// CreateAccessRight provides a mock function with given fields: ctx, req
func (_m *IAccessUseCase) CreateAccessRight(ctx context.Context, req model.CreateAccessRightRequest) (*model.AccessRightResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessRight")
	}

	var r0 *model.AccessRightResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateAccessRightRequest) (*model.AccessRightResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateAccessRightRequest) *model.AccessRightResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccessRightResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateAccessRightRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateEndpoint provides a mock function with given fields: ctx, req
func (_m *IAccessUseCase) CreateEndpoint(ctx context.Context, req model.CreateEndpointRequest) (*model.EndpointResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateEndpoint")
	}

	var r0 *model.EndpointResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateEndpointRequest) (*model.EndpointResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateEndpointRequest) *model.EndpointResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.EndpointResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateEndpointRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllAccessRights provides a mock function with given fields: ctx
func (_m *IAccessUseCase) GetAllAccessRights(ctx context.Context) (*model.AccessRightListResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAccessRights")
	}

	var r0 *model.AccessRightListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.AccessRightListResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.AccessRightListResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccessRightListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkEndpointToAccessRight provides a mock function with given fields: ctx, req
func (_m *IAccessUseCase) LinkEndpointToAccessRight(ctx context.Context, req model.LinkEndpointRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for LinkEndpointToAccessRight")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.LinkEndpointRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAccessUseCase creates a new instance of IAccessUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAccessUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAccessUseCase {
	mock := &IAccessUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
