// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/access/model"
	querybuilder "github.com/Roisfaozi/go-clean-boilerplate/pkg/querybuilder"
	mock "github.com/stretchr/testify/mock"
)

// MockIAccessUseCase is an autogenerated mock type for the IAccessUseCase type
type MockIAccessUseCase struct {
	mock.Mock
}

type MockIAccessUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAccessUseCase) EXPECT() *MockIAccessUseCase_Expecter {
	return &MockIAccessUseCase_Expecter{mock: &_m.Mock}
}

// CreateAccessRight provides a mock function with given fields: ctx, req
func (_m *MockIAccessUseCase) CreateAccessRight(ctx context.Context, req model.CreateAccessRightRequest) (*model.AccessRightResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessRight")
	}

	var r0 *model.AccessRightResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateAccessRightRequest) (*model.AccessRightResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateAccessRightRequest) *model.AccessRightResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccessRightResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateAccessRightRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAccessUseCase_CreateAccessRight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccessRight'
type MockIAccessUseCase_CreateAccessRight_Call struct {
	*mock.Call
}

// CreateAccessRight is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.CreateAccessRightRequest
func (_e *MockIAccessUseCase_Expecter) CreateAccessRight(ctx interface{}, req interface{}) *MockIAccessUseCase_CreateAccessRight_Call {
	return &MockIAccessUseCase_CreateAccessRight_Call{Call: _e.mock.On("CreateAccessRight", ctx, req)}
}

func (_c *MockIAccessUseCase_CreateAccessRight_Call) Run(run func(ctx context.Context, req model.CreateAccessRightRequest)) *MockIAccessUseCase_CreateAccessRight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateAccessRightRequest))
	})
	return _c
}

func (_c *MockIAccessUseCase_CreateAccessRight_Call) Return(_a0 *model.AccessRightResponse, _a1 error) *MockIAccessUseCase_CreateAccessRight_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAccessUseCase_CreateAccessRight_Call) RunAndReturn(run func(context.Context, model.CreateAccessRightRequest) (*model.AccessRightResponse, error)) *MockIAccessUseCase_CreateAccessRight_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEndpoint provides a mock function with given fields: ctx, req
func (_m *MockIAccessUseCase) CreateEndpoint(ctx context.Context, req model.CreateEndpointRequest) (*model.EndpointResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateEndpoint")
	}

	var r0 *model.EndpointResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateEndpointRequest) (*model.EndpointResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateEndpointRequest) *model.EndpointResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.EndpointResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateEndpointRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAccessUseCase_CreateEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEndpoint'
type MockIAccessUseCase_CreateEndpoint_Call struct {
	*mock.Call
}

// CreateEndpoint is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.CreateEndpointRequest
func (_e *MockIAccessUseCase_Expecter) CreateEndpoint(ctx interface{}, req interface{}) *MockIAccessUseCase_CreateEndpoint_Call {
	return &MockIAccessUseCase_CreateEndpoint_Call{Call: _e.mock.On("CreateEndpoint", ctx, req)}
}

func (_c *MockIAccessUseCase_CreateEndpoint_Call) Run(run func(ctx context.Context, req model.CreateEndpointRequest)) *MockIAccessUseCase_CreateEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateEndpointRequest))
	})
	return _c
}

func (_c *MockIAccessUseCase_CreateEndpoint_Call) Return(_a0 *model.EndpointResponse, _a1 error) *MockIAccessUseCase_CreateEndpoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAccessUseCase_CreateEndpoint_Call) RunAndReturn(run func(context.Context, model.CreateEndpointRequest) (*model.EndpointResponse, error)) *MockIAccessUseCase_CreateEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccessRight provides a mock function with given fields: ctx, id
func (_m *MockIAccessUseCase) DeleteAccessRight(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessRight")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAccessUseCase_DeleteAccessRight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccessRight'
type MockIAccessUseCase_DeleteAccessRight_Call struct {
	*mock.Call
}

// DeleteAccessRight is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIAccessUseCase_Expecter) DeleteAccessRight(ctx interface{}, id interface{}) *MockIAccessUseCase_DeleteAccessRight_Call {
	return &MockIAccessUseCase_DeleteAccessRight_Call{Call: _e.mock.On("DeleteAccessRight", ctx, id)}
}

func (_c *MockIAccessUseCase_DeleteAccessRight_Call) Run(run func(ctx context.Context, id string)) *MockIAccessUseCase_DeleteAccessRight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAccessUseCase_DeleteAccessRight_Call) Return(_a0 error) *MockIAccessUseCase_DeleteAccessRight_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAccessUseCase_DeleteAccessRight_Call) RunAndReturn(run func(context.Context, string) error) *MockIAccessUseCase_DeleteAccessRight_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEndpoint provides a mock function with given fields: ctx, id
func (_m *MockIAccessUseCase) DeleteEndpoint(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEndpoint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAccessUseCase_DeleteEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEndpoint'
type MockIAccessUseCase_DeleteEndpoint_Call struct {
	*mock.Call
}

// DeleteEndpoint is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIAccessUseCase_Expecter) DeleteEndpoint(ctx interface{}, id interface{}) *MockIAccessUseCase_DeleteEndpoint_Call {
	return &MockIAccessUseCase_DeleteEndpoint_Call{Call: _e.mock.On("DeleteEndpoint", ctx, id)}
}

func (_c *MockIAccessUseCase_DeleteEndpoint_Call) Run(run func(ctx context.Context, id string)) *MockIAccessUseCase_DeleteEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIAccessUseCase_DeleteEndpoint_Call) Return(_a0 error) *MockIAccessUseCase_DeleteEndpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAccessUseCase_DeleteEndpoint_Call) RunAndReturn(run func(context.Context, string) error) *MockIAccessUseCase_DeleteEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessRightsDynamic provides a mock function with given fields: ctx, filter
func (_m *MockIAccessUseCase) GetAccessRightsDynamic(ctx context.Context, filter *querybuilder.DynamicFilter) (*model.AccessRightListResponse, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessRightsDynamic")
	}

	var r0 *model.AccessRightListResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) (*model.AccessRightListResponse, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) *model.AccessRightListResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccessRightListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querybuilder.DynamicFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *querybuilder.DynamicFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAccessUseCase_GetAccessRightsDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessRightsDynamic'
type MockIAccessUseCase_GetAccessRightsDynamic_Call struct {
	*mock.Call
}

// GetAccessRightsDynamic is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *querybuilder.DynamicFilter
func (_e *MockIAccessUseCase_Expecter) GetAccessRightsDynamic(ctx interface{}, filter interface{}) *MockIAccessUseCase_GetAccessRightsDynamic_Call {
	return &MockIAccessUseCase_GetAccessRightsDynamic_Call{Call: _e.mock.On("GetAccessRightsDynamic", ctx, filter)}
}

func (_c *MockIAccessUseCase_GetAccessRightsDynamic_Call) Run(run func(ctx context.Context, filter *querybuilder.DynamicFilter)) *MockIAccessUseCase_GetAccessRightsDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querybuilder.DynamicFilter))
	})
	return _c
}

func (_c *MockIAccessUseCase_GetAccessRightsDynamic_Call) Return(_a0 *model.AccessRightListResponse, _a1 int64, _a2 error) *MockIAccessUseCase_GetAccessRightsDynamic_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAccessUseCase_GetAccessRightsDynamic_Call) RunAndReturn(run func(context.Context, *querybuilder.DynamicFilter) (*model.AccessRightListResponse, int64, error)) *MockIAccessUseCase_GetAccessRightsDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAccessRights provides a mock function with given fields: ctx
func (_m *MockIAccessUseCase) GetAllAccessRights(ctx context.Context) (*model.AccessRightListResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAccessRights")
	}

	var r0 *model.AccessRightListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.AccessRightListResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.AccessRightListResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccessRightListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAccessUseCase_GetAllAccessRights_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAccessRights'
type MockIAccessUseCase_GetAllAccessRights_Call struct {
	*mock.Call
}

// GetAllAccessRights is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIAccessUseCase_Expecter) GetAllAccessRights(ctx interface{}) *MockIAccessUseCase_GetAllAccessRights_Call {
	return &MockIAccessUseCase_GetAllAccessRights_Call{Call: _e.mock.On("GetAllAccessRights", ctx)}
}

func (_c *MockIAccessUseCase_GetAllAccessRights_Call) Run(run func(ctx context.Context)) *MockIAccessUseCase_GetAllAccessRights_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIAccessUseCase_GetAllAccessRights_Call) Return(_a0 *model.AccessRightListResponse, _a1 error) *MockIAccessUseCase_GetAllAccessRights_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAccessUseCase_GetAllAccessRights_Call) RunAndReturn(run func(context.Context) (*model.AccessRightListResponse, error)) *MockIAccessUseCase_GetAllAccessRights_Call {
	_c.Call.Return(run)
	return _c
}

// GetEndpointsDynamic provides a mock function with given fields: ctx, filter
func (_m *MockIAccessUseCase) GetEndpointsDynamic(ctx context.Context, filter *querybuilder.DynamicFilter) ([]*model.EndpointResponse, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetEndpointsDynamic")
	}

	var r0 []*model.EndpointResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) ([]*model.EndpointResponse, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) []*model.EndpointResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.EndpointResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querybuilder.DynamicFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *querybuilder.DynamicFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAccessUseCase_GetEndpointsDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndpointsDynamic'
type MockIAccessUseCase_GetEndpointsDynamic_Call struct {
	*mock.Call
}

// GetEndpointsDynamic is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *querybuilder.DynamicFilter
func (_e *MockIAccessUseCase_Expecter) GetEndpointsDynamic(ctx interface{}, filter interface{}) *MockIAccessUseCase_GetEndpointsDynamic_Call {
	return &MockIAccessUseCase_GetEndpointsDynamic_Call{Call: _e.mock.On("GetEndpointsDynamic", ctx, filter)}
}

func (_c *MockIAccessUseCase_GetEndpointsDynamic_Call) Run(run func(ctx context.Context, filter *querybuilder.DynamicFilter)) *MockIAccessUseCase_GetEndpointsDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querybuilder.DynamicFilter))
	})
	return _c
}

func (_c *MockIAccessUseCase_GetEndpointsDynamic_Call) Return(_a0 []*model.EndpointResponse, _a1 int64, _a2 error) *MockIAccessUseCase_GetEndpointsDynamic_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAccessUseCase_GetEndpointsDynamic_Call) RunAndReturn(run func(context.Context, *querybuilder.DynamicFilter) ([]*model.EndpointResponse, int64, error)) *MockIAccessUseCase_GetEndpointsDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// LinkEndpointToAccessRight provides a mock function with given fields: ctx, req
func (_m *MockIAccessUseCase) LinkEndpointToAccessRight(ctx context.Context, req model.LinkEndpointRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for LinkEndpointToAccessRight")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.LinkEndpointRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAccessUseCase_LinkEndpointToAccessRight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkEndpointToAccessRight'
type MockIAccessUseCase_LinkEndpointToAccessRight_Call struct {
	*mock.Call
}

// LinkEndpointToAccessRight is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.LinkEndpointRequest
func (_e *MockIAccessUseCase_Expecter) LinkEndpointToAccessRight(ctx interface{}, req interface{}) *MockIAccessUseCase_LinkEndpointToAccessRight_Call {
	return &MockIAccessUseCase_LinkEndpointToAccessRight_Call{Call: _e.mock.On("LinkEndpointToAccessRight", ctx, req)}
}

func (_c *MockIAccessUseCase_LinkEndpointToAccessRight_Call) Run(run func(ctx context.Context, req model.LinkEndpointRequest)) *MockIAccessUseCase_LinkEndpointToAccessRight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.LinkEndpointRequest))
	})
	return _c
}

func (_c *MockIAccessUseCase_LinkEndpointToAccessRight_Call) Return(_a0 error) *MockIAccessUseCase_LinkEndpointToAccessRight_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAccessUseCase_LinkEndpointToAccessRight_Call) RunAndReturn(run func(context.Context, model.LinkEndpointRequest) error) *MockIAccessUseCase_LinkEndpointToAccessRight_Call {
	_c.Call.Return(run)
	return _c
}

// UnlinkEndpointFromAccessRight provides a mock function with given fields: ctx, req
func (_m *MockIAccessUseCase) UnlinkEndpointFromAccessRight(ctx context.Context, req model.LinkEndpointRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UnlinkEndpointFromAccessRight")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.LinkEndpointRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAccessUseCase_UnlinkEndpointFromAccessRight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlinkEndpointFromAccessRight'
type MockIAccessUseCase_UnlinkEndpointFromAccessRight_Call struct {
	*mock.Call
}

// UnlinkEndpointFromAccessRight is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.LinkEndpointRequest
func (_e *MockIAccessUseCase_Expecter) UnlinkEndpointFromAccessRight(ctx interface{}, req interface{}) *MockIAccessUseCase_UnlinkEndpointFromAccessRight_Call {
	return &MockIAccessUseCase_UnlinkEndpointFromAccessRight_Call{Call: _e.mock.On("UnlinkEndpointFromAccessRight", ctx, req)}
}

func (_c *MockIAccessUseCase_UnlinkEndpointFromAccessRight_Call) Run(run func(ctx context.Context, req model.LinkEndpointRequest)) *MockIAccessUseCase_UnlinkEndpointFromAccessRight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.LinkEndpointRequest))
	})
	return _c
}

func (_c *MockIAccessUseCase_UnlinkEndpointFromAccessRight_Call) Return(_a0 error) *MockIAccessUseCase_UnlinkEndpointFromAccessRight_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAccessUseCase_UnlinkEndpointFromAccessRight_Call) RunAndReturn(run func(context.Context, model.LinkEndpointRequest) error) *MockIAccessUseCase_UnlinkEndpointFromAccessRight_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAccessUseCase creates a new instance of MockIAccessUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAccessUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAccessUseCase {
	mock := &MockIAccessUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
