// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/Roisfaozi/casbin-db/internal/modules/role/model"
	mock "github.com/stretchr/testify/mock"
)

// RoleUseCase is an autogenerated mock type for the RoleUseCase type
type RoleUseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *RoleUseCase) Create(ctx context.Context, req *model.CreateRoleRequest) (*model.RoleResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.RoleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateRoleRequest) (*model.RoleResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateRoleRequest) *model.RoleResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RoleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreateRoleRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *RoleUseCase) GetAll(ctx context.Context) ([]model.RoleResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.RoleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.RoleResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.RoleResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RoleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRoleUseCase creates a new instance of RoleUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleUseCase {
	mock := &RoleUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
