// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockpolicyReloader is an autogenerated mock type for the policyReloader type
type MockpolicyReloader struct {
	mock.Mock
}

type MockpolicyReloader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockpolicyReloader) EXPECT() *MockpolicyReloader_Expecter {
	return &MockpolicyReloader_Expecter{mock: &_m.Mock}
}

// ReloadPolicy provides a mock function with given fields: ctx
func (_m *MockpolicyReloader) ReloadPolicy(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReloadPolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockpolicyReloader_ReloadPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReloadPolicy'
type MockpolicyReloader_ReloadPolicy_Call struct {
	*mock.Call
}

// ReloadPolicy is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockpolicyReloader_Expecter) ReloadPolicy(ctx interface{}) *MockpolicyReloader_ReloadPolicy_Call {
	return &MockpolicyReloader_ReloadPolicy_Call{Call: _e.mock.On("ReloadPolicy", ctx)}
}

func (_c *MockpolicyReloader_ReloadPolicy_Call) Run(run func(ctx context.Context)) *MockpolicyReloader_ReloadPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockpolicyReloader_ReloadPolicy_Call) Return(_a0 error) *MockpolicyReloader_ReloadPolicy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockpolicyReloader_ReloadPolicy_Call) RunAndReturn(run func(context.Context) error) *MockpolicyReloader_ReloadPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockpolicyReloader creates a new instance of MockpolicyReloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockpolicyReloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockpolicyReloader {
	mock := &MockpolicyReloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
