// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/role/entity"
	mock "github.com/stretchr/testify/mock"

	querybuilder "github.com/Roisfaozi/go-clean-boilerplate/pkg/querybuilder"
)

// MockRoleRepository is an autogenerated mock type for the RoleRepository type
type MockRoleRepository struct {
	mock.Mock
}

type MockRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepository) EXPECT() *MockRoleRepository_Expecter {
	return &MockRoleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, role
func (_m *MockRoleRepository) Create(ctx context.Context, role *entity.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - role *entity.Role
func (_e *MockRoleRepository_Expecter) Create(ctx interface{}, role interface{}) *MockRoleRepository_Create_Call {
	return &MockRoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, role)}
}

func (_c *MockRoleRepository_Create_Call) Run(run func(ctx context.Context, role *entity.Role)) *MockRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Role))
	})
	return _c
}

func (_c *MockRoleRepository_Create_Call) Return(_a0 error) *MockRoleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Role) error) *MockRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRoleRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoleRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRoleRepository_Delete_Call {
	return &MockRoleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoleRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockRoleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_Delete_Call) Return(_a0 error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockRoleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInOrg provides a mock function with given fields: ctx, orgID, roleID
func (_m *MockRoleRepository) DeleteInOrg(ctx context.Context, orgID string, roleID string) error {
	ret := _m.Called(ctx, orgID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInOrg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orgID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_DeleteInOrg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInOrg'
type MockRoleRepository_DeleteInOrg_Call struct {
	*mock.Call
}

// DeleteInOrg is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - roleID string
func (_e *MockRoleRepository_Expecter) DeleteInOrg(ctx interface{}, orgID interface{}, roleID interface{}) *MockRoleRepository_DeleteInOrg_Call {
	return &MockRoleRepository_DeleteInOrg_Call{Call: _e.mock.On("DeleteInOrg", ctx, orgID, roleID)}
}

func (_c *MockRoleRepository_DeleteInOrg_Call) Run(run func(ctx context.Context, orgID string, roleID string)) *MockRoleRepository_DeleteInOrg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoleRepository_DeleteInOrg_Call) Return(_a0 error) *MockRoleRepository_DeleteInOrg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_DeleteInOrg_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRoleRepository_DeleteInOrg_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockRoleRepository) FindAll(ctx context.Context) ([]*entity.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entity.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRoleRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoleRepository_Expecter) FindAll(ctx interface{}) *MockRoleRepository_FindAll_Call {
	return &MockRoleRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockRoleRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockRoleRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRoleRepository_FindAll_Call) Return(_a0 []*entity.Role, _a1 error) *MockRoleRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindAll_Call) RunAndReturn(run func(context.Context) ([]*entity.Role, error)) *MockRoleRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllDynamic provides a mock function with given fields: ctx, filter
func (_m *MockRoleRepository) FindAllDynamic(ctx context.Context, filter *querybuilder.DynamicFilter) ([]*entity.Role, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAllDynamic")
	}

	var r0 []*entity.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) ([]*entity.Role, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) []*entity.Role); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querybuilder.DynamicFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindAllDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllDynamic'
type MockRoleRepository_FindAllDynamic_Call struct {
	*mock.Call
}

// FindAllDynamic is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *querybuilder.DynamicFilter
func (_e *MockRoleRepository_Expecter) FindAllDynamic(ctx interface{}, filter interface{}) *MockRoleRepository_FindAllDynamic_Call {
	return &MockRoleRepository_FindAllDynamic_Call{Call: _e.mock.On("FindAllDynamic", ctx, filter)}
}

func (_c *MockRoleRepository_FindAllDynamic_Call) Run(run func(ctx context.Context, filter *querybuilder.DynamicFilter)) *MockRoleRepository_FindAllDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querybuilder.DynamicFilter))
	})
	return _c
}

func (_c *MockRoleRepository_FindAllDynamic_Call) Return(_a0 []*entity.Role, _a1 error) *MockRoleRepository_FindAllDynamic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindAllDynamic_Call) RunAndReturn(run func(context.Context, *querybuilder.DynamicFilter) ([]*entity.Role, error)) *MockRoleRepository_FindAllDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockRoleRepository) FindByID(ctx context.Context, id string) (*entity.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Role); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRoleRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRoleRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRoleRepository_FindByID_Call {
	return &MockRoleRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRoleRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockRoleRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_FindByID_Call) Return(_a0 *entity.Role, _a1 error) *MockRoleRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*entity.Role, error)) *MockRoleRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MockRoleRepository) FindByName(ctx context.Context, name string) (*entity.Role, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *entity.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Role, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Role); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockRoleRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockRoleRepository_FindByName_Call {
	return &MockRoleRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockRoleRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockRoleRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_FindByName_Call) Return(_a0 *entity.Role, _a1 error) *MockRoleRepository_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindByName_Call) RunAndReturn(run func(context.Context, string) (*entity.Role, error)) *MockRoleRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindByNameInScope provides a mock function with given fields: ctx, name, orgID
func (_m *MockRoleRepository) FindByNameInScope(ctx context.Context, name string, orgID *string) (*entity.Role, error) {
	ret := _m.Called(ctx, name, orgID)

	if len(ret) == 0 {
		panic("no return value specified for FindByNameInScope")
	}

	var r0 *entity.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) (*entity.Role, error)); ok {
		return rf(ctx, name, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) *entity.Role); ok {
		r0 = rf(ctx, name, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string) error); ok {
		r1 = rf(ctx, name, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindByNameInScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNameInScope'
type MockRoleRepository_FindByNameInScope_Call struct {
	*mock.Call
}

// FindByNameInScope is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - orgID *string
func (_e *MockRoleRepository_Expecter) FindByNameInScope(ctx interface{}, name interface{}, orgID interface{}) *MockRoleRepository_FindByNameInScope_Call {
	return &MockRoleRepository_FindByNameInScope_Call{Call: _e.mock.On("FindByNameInScope", ctx, name, orgID)}
}

func (_c *MockRoleRepository_FindByNameInScope_Call) Run(run func(ctx context.Context, name string, orgID *string)) *MockRoleRepository_FindByNameInScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string))
	})
	return _c
}

func (_c *MockRoleRepository_FindByNameInScope_Call) Return(_a0 *entity.Role, _a1 error) *MockRoleRepository_FindByNameInScope_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindByNameInScope_Call) RunAndReturn(run func(context.Context, string, *string) (*entity.Role, error)) *MockRoleRepository_FindByNameInScope_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrganizationRoleByID provides a mock function with given fields: ctx, organizationID, roleID
func (_m *MockRoleRepository) FindOrganizationRoleByID(ctx context.Context, organizationID string, roleID string) (*entity.Role, error) {
	ret := _m.Called(ctx, organizationID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for FindOrganizationRoleByID")
	}

	var r0 *entity.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entity.Role, error)); ok {
		return rf(ctx, organizationID, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.Role); ok {
		r0 = rf(ctx, organizationID, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, organizationID, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindOrganizationRoleByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrganizationRoleByID'
type MockRoleRepository_FindOrganizationRoleByID_Call struct {
	*mock.Call
}

// FindOrganizationRoleByID is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - roleID string
func (_e *MockRoleRepository_Expecter) FindOrganizationRoleByID(ctx interface{}, organizationID interface{}, roleID interface{}) *MockRoleRepository_FindOrganizationRoleByID_Call {
	return &MockRoleRepository_FindOrganizationRoleByID_Call{Call: _e.mock.On("FindOrganizationRoleByID", ctx, organizationID, roleID)}
}

func (_c *MockRoleRepository_FindOrganizationRoleByID_Call) Run(run func(ctx context.Context, organizationID string, roleID string)) *MockRoleRepository_FindOrganizationRoleByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRoleRepository_FindOrganizationRoleByID_Call) Return(_a0 *entity.Role, _a1 error) *MockRoleRepository_FindOrganizationRoleByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindOrganizationRoleByID_Call) RunAndReturn(run func(context.Context, string, string) (*entity.Role, error)) *MockRoleRepository_FindOrganizationRoleByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrganizationRoles provides a mock function with given fields: ctx, organizationID
func (_m *MockRoleRepository) FindOrganizationRoles(ctx context.Context, organizationID string) ([]*entity.Role, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for FindOrganizationRoles")
	}

	var r0 []*entity.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Role, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entity.Role); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepository_FindOrganizationRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrganizationRoles'
type MockRoleRepository_FindOrganizationRoles_Call struct {
	*mock.Call
}

// FindOrganizationRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
func (_e *MockRoleRepository_Expecter) FindOrganizationRoles(ctx interface{}, organizationID interface{}) *MockRoleRepository_FindOrganizationRoles_Call {
	return &MockRoleRepository_FindOrganizationRoles_Call{Call: _e.mock.On("FindOrganizationRoles", ctx, organizationID)}
}

func (_c *MockRoleRepository_FindOrganizationRoles_Call) Run(run func(ctx context.Context, organizationID string)) *MockRoleRepository_FindOrganizationRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepository_FindOrganizationRoles_Call) Return(_a0 []*entity.Role, _a1 error) *MockRoleRepository_FindOrganizationRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepository_FindOrganizationRoles_Call) RunAndReturn(run func(context.Context, string) ([]*entity.Role, error)) *MockRoleRepository_FindOrganizationRoles_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, role
func (_m *MockRoleRepository) Update(ctx context.Context, role *entity.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - role *entity.Role
func (_e *MockRoleRepository_Expecter) Update(ctx interface{}, role interface{}) *MockRoleRepository_Update_Call {
	return &MockRoleRepository_Update_Call{Call: _e.mock.On("Update", ctx, role)}
}

func (_c *MockRoleRepository_Update_Call) Run(run func(ctx context.Context, role *entity.Role)) *MockRoleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Role))
	})
	return _c
}

func (_c *MockRoleRepository_Update_Call) Return(_a0 error) *MockRoleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoleRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Role) error) *MockRoleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleRepository creates a new instance of MockRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepository {
	mock := &MockRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
