// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocking

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	ws "github.com/Roisfaozi/go-clean-boilerplate/pkg/ws"
)

// MockPresenceManager is an autogenerated mock type for the PresenceManager type
type MockPresenceManager struct {
	mock.Mock
}

type MockPresenceManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPresenceManager) EXPECT() *MockPresenceManager_Expecter {
	return &MockPresenceManager_Expecter{mock: &_m.Mock}
}

// GetOnlineUsers provides a mock function with given fields: ctx, orgID
func (_m *MockPresenceManager) GetOnlineUsers(ctx context.Context, orgID string) ([]ws.PresenceUser, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetOnlineUsers")
	}

	var r0 []ws.PresenceUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]ws.PresenceUser, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []ws.PresenceUser); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ws.PresenceUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPresenceManager_GetOnlineUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOnlineUsers'
type MockPresenceManager_GetOnlineUsers_Call struct {
	*mock.Call
}

// GetOnlineUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockPresenceManager_Expecter) GetOnlineUsers(ctx interface{}, orgID interface{}) *MockPresenceManager_GetOnlineUsers_Call {
	return &MockPresenceManager_GetOnlineUsers_Call{Call: _e.mock.On("GetOnlineUsers", ctx, orgID)}
}

func (_c *MockPresenceManager_GetOnlineUsers_Call) Run(run func(ctx context.Context, orgID string)) *MockPresenceManager_GetOnlineUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPresenceManager_GetOnlineUsers_Call) Return(_a0 []ws.PresenceUser, _a1 error) *MockPresenceManager_GetOnlineUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPresenceManager_GetOnlineUsers_Call) RunAndReturn(run func(context.Context, string) ([]ws.PresenceUser, error)) *MockPresenceManager_GetOnlineUsers_Call {
	_c.Call.Return(run)
	return _c
}

// PruneStaleUsers provides a mock function with given fields: ctx, timeout
func (_m *MockPresenceManager) PruneStaleUsers(ctx context.Context, timeout time.Duration) (map[string][]string, error) {
	ret := _m.Called(ctx, timeout)

	if len(ret) == 0 {
		panic("no return value specified for PruneStaleUsers")
	}

	var r0 map[string][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) (map[string][]string, error)); ok {
		return rf(ctx, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) map[string][]string); ok {
		r0 = rf(ctx, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPresenceManager_PruneStaleUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneStaleUsers'
type MockPresenceManager_PruneStaleUsers_Call struct {
	*mock.Call
}

// PruneStaleUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
func (_e *MockPresenceManager_Expecter) PruneStaleUsers(ctx interface{}, timeout interface{}) *MockPresenceManager_PruneStaleUsers_Call {
	return &MockPresenceManager_PruneStaleUsers_Call{Call: _e.mock.On("PruneStaleUsers", ctx, timeout)}
}

func (_c *MockPresenceManager_PruneStaleUsers_Call) Run(run func(ctx context.Context, timeout time.Duration)) *MockPresenceManager_PruneStaleUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockPresenceManager_PruneStaleUsers_Call) Return(_a0 map[string][]string, _a1 error) *MockPresenceManager_PruneStaleUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPresenceManager_PruneStaleUsers_Call) RunAndReturn(run func(context.Context, time.Duration) (map[string][]string, error)) *MockPresenceManager_PruneStaleUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshUserHeartbeat provides a mock function with given fields: ctx, orgID, userID
func (_m *MockPresenceManager) RefreshUserHeartbeat(ctx context.Context, orgID string, userID string) error {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RefreshUserHeartbeat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPresenceManager_RefreshUserHeartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshUserHeartbeat'
type MockPresenceManager_RefreshUserHeartbeat_Call struct {
	*mock.Call
}

// RefreshUserHeartbeat is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockPresenceManager_Expecter) RefreshUserHeartbeat(ctx interface{}, orgID interface{}, userID interface{}) *MockPresenceManager_RefreshUserHeartbeat_Call {
	return &MockPresenceManager_RefreshUserHeartbeat_Call{Call: _e.mock.On("RefreshUserHeartbeat", ctx, orgID, userID)}
}

func (_c *MockPresenceManager_RefreshUserHeartbeat_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockPresenceManager_RefreshUserHeartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPresenceManager_RefreshUserHeartbeat_Call) Return(_a0 error) *MockPresenceManager_RefreshUserHeartbeat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPresenceManager_RefreshUserHeartbeat_Call) RunAndReturn(run func(context.Context, string, string) error) *MockPresenceManager_RefreshUserHeartbeat_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserOffline provides a mock function with given fields: ctx, orgID, userID
func (_m *MockPresenceManager) SetUserOffline(ctx context.Context, orgID string, userID string) error {
	ret := _m.Called(ctx, orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for SetUserOffline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orgID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPresenceManager_SetUserOffline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserOffline'
type MockPresenceManager_SetUserOffline_Call struct {
	*mock.Call
}

// SetUserOffline is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
func (_e *MockPresenceManager_Expecter) SetUserOffline(ctx interface{}, orgID interface{}, userID interface{}) *MockPresenceManager_SetUserOffline_Call {
	return &MockPresenceManager_SetUserOffline_Call{Call: _e.mock.On("SetUserOffline", ctx, orgID, userID)}
}

func (_c *MockPresenceManager_SetUserOffline_Call) Run(run func(ctx context.Context, orgID string, userID string)) *MockPresenceManager_SetUserOffline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPresenceManager_SetUserOffline_Call) Return(_a0 error) *MockPresenceManager_SetUserOffline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPresenceManager_SetUserOffline_Call) RunAndReturn(run func(context.Context, string, string) error) *MockPresenceManager_SetUserOffline_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserOnline provides a mock function with given fields: ctx, orgID, userID, userData
func (_m *MockPresenceManager) SetUserOnline(ctx context.Context, orgID string, userID string, userData *ws.PresenceUser) error {
	ret := _m.Called(ctx, orgID, userID, userData)

	if len(ret) == 0 {
		panic("no return value specified for SetUserOnline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *ws.PresenceUser) error); ok {
		r0 = rf(ctx, orgID, userID, userData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPresenceManager_SetUserOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserOnline'
type MockPresenceManager_SetUserOnline_Call struct {
	*mock.Call
}

// SetUserOnline is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - userID string
//   - userData *ws.PresenceUser
func (_e *MockPresenceManager_Expecter) SetUserOnline(ctx interface{}, orgID interface{}, userID interface{}, userData interface{}) *MockPresenceManager_SetUserOnline_Call {
	return &MockPresenceManager_SetUserOnline_Call{Call: _e.mock.On("SetUserOnline", ctx, orgID, userID, userData)}
}

func (_c *MockPresenceManager_SetUserOnline_Call) Run(run func(ctx context.Context, orgID string, userID string, userData *ws.PresenceUser)) *MockPresenceManager_SetUserOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*ws.PresenceUser))
	})
	return _c
}

func (_c *MockPresenceManager_SetUserOnline_Call) Return(_a0 error) *MockPresenceManager_SetUserOnline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPresenceManager_SetUserOnline_Call) RunAndReturn(run func(context.Context, string, string, *ws.PresenceUser) error) *MockPresenceManager_SetUserOnline_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPresenceManager creates a new instance of MockPresenceManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPresenceManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPresenceManager {
	mock := &MockPresenceManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
