// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocking

import (
	ws "github.com/Roisfaozi/go-clean-boilerplate/pkg/ws"
	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// BroadcastToChannel provides a mock function with given fields: channel, message
func (_m *MockManager) BroadcastToChannel(channel string, message []byte) {
	_m.Called(channel, message)
}

// MockManager_BroadcastToChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastToChannel'
type MockManager_BroadcastToChannel_Call struct {
	*mock.Call
}

// BroadcastToChannel is a helper method to define mock.On call
//   - channel string
//   - message []byte
func (_e *MockManager_Expecter) BroadcastToChannel(channel interface{}, message interface{}) *MockManager_BroadcastToChannel_Call {
	return &MockManager_BroadcastToChannel_Call{Call: _e.mock.On("BroadcastToChannel", channel, message)}
}

func (_c *MockManager_BroadcastToChannel_Call) Run(run func(channel string, message []byte)) *MockManager_BroadcastToChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *MockManager_BroadcastToChannel_Call) Return() *MockManager_BroadcastToChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_BroadcastToChannel_Call) RunAndReturn(run func(string, []byte)) *MockManager_BroadcastToChannel_Call {
	_c.Run(run)
	return _c
}

// GetChannelClients provides a mock function with given fields: channel
func (_m *MockManager) GetChannelClients(channel string) int {
	ret := _m.Called(channel)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelClients")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(channel)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockManager_GetChannelClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelClients'
type MockManager_GetChannelClients_Call struct {
	*mock.Call
}

// GetChannelClients is a helper method to define mock.On call
//   - channel string
func (_e *MockManager_Expecter) GetChannelClients(channel interface{}) *MockManager_GetChannelClients_Call {
	return &MockManager_GetChannelClients_Call{Call: _e.mock.On("GetChannelClients", channel)}
}

func (_c *MockManager_GetChannelClients_Call) Run(run func(channel string)) *MockManager_GetChannelClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockManager_GetChannelClients_Call) Return(_a0 int) *MockManager_GetChannelClients_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_GetChannelClients_Call) RunAndReturn(run func(string) int) *MockManager_GetChannelClients_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresenceManager provides a mock function with no fields
func (_m *MockManager) GetPresenceManager() ws.PresenceManager {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPresenceManager")
	}

	var r0 ws.PresenceManager
	if rf, ok := ret.Get(0).(func() ws.PresenceManager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ws.PresenceManager)
		}
	}

	return r0
}

// MockManager_GetPresenceManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresenceManager'
type MockManager_GetPresenceManager_Call struct {
	*mock.Call
}

// GetPresenceManager is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetPresenceManager() *MockManager_GetPresenceManager_Call {
	return &MockManager_GetPresenceManager_Call{Call: _e.mock.On("GetPresenceManager")}
}

func (_c *MockManager_GetPresenceManager_Call) Run(run func()) *MockManager_GetPresenceManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetPresenceManager_Call) Return(_a0 ws.PresenceManager) *MockManager_GetPresenceManager_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_GetPresenceManager_Call) RunAndReturn(run func() ws.PresenceManager) *MockManager_GetPresenceManager_Call {
	_c.Call.Return(run)
	return _c
}

// PresenceUpdate provides a mock function with given fields: orgID, event, userData
func (_m *MockManager) PresenceUpdate(orgID string, event string, userData *ws.PresenceUser) {
	_m.Called(orgID, event, userData)
}

// MockManager_PresenceUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresenceUpdate'
type MockManager_PresenceUpdate_Call struct {
	*mock.Call
}

// PresenceUpdate is a helper method to define mock.On call
//   - orgID string
//   - event string
//   - userData *ws.PresenceUser
func (_e *MockManager_Expecter) PresenceUpdate(orgID interface{}, event interface{}, userData interface{}) *MockManager_PresenceUpdate_Call {
	return &MockManager_PresenceUpdate_Call{Call: _e.mock.On("PresenceUpdate", orgID, event, userData)}
}

func (_c *MockManager_PresenceUpdate_Call) Run(run func(orgID string, event string, userData *ws.PresenceUser)) *MockManager_PresenceUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(*ws.PresenceUser))
	})
	return _c
}

func (_c *MockManager_PresenceUpdate_Call) Return() *MockManager_PresenceUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_PresenceUpdate_Call) RunAndReturn(run func(string, string, *ws.PresenceUser)) *MockManager_PresenceUpdate_Call {
	_c.Run(run)
	return _c
}

// RegisterClient provides a mock function with given fields: client
func (_m *MockManager) RegisterClient(client *ws.Client) {
	_m.Called(client)
}

// MockManager_RegisterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterClient'
type MockManager_RegisterClient_Call struct {
	*mock.Call
}

// RegisterClient is a helper method to define mock.On call
//   - client *ws.Client
func (_e *MockManager_Expecter) RegisterClient(client interface{}) *MockManager_RegisterClient_Call {
	return &MockManager_RegisterClient_Call{Call: _e.mock.On("RegisterClient", client)}
}

func (_c *MockManager_RegisterClient_Call) Run(run func(client *ws.Client)) *MockManager_RegisterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ws.Client))
	})
	return _c
}

func (_c *MockManager_RegisterClient_Call) Return() *MockManager_RegisterClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_RegisterClient_Call) RunAndReturn(run func(*ws.Client)) *MockManager_RegisterClient_Call {
	_c.Run(run)
	return _c
}

// Run provides a mock function with no fields
func (_m *MockManager) Run() {
	_m.Called()
}

// MockManager_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockManager_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockManager_Expecter) Run() *MockManager_Run_Call {
	return &MockManager_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockManager_Run_Call) Run(run func()) *MockManager_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Run_Call) Return() *MockManager_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_Run_Call) RunAndReturn(run func()) *MockManager_Run_Call {
	_c.Run(run)
	return _c
}

// SubscribeToChannel provides a mock function with given fields: client, channel
func (_m *MockManager) SubscribeToChannel(client *ws.Client, channel string) {
	_m.Called(client, channel)
}

// MockManager_SubscribeToChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeToChannel'
type MockManager_SubscribeToChannel_Call struct {
	*mock.Call
}

// SubscribeToChannel is a helper method to define mock.On call
//   - client *ws.Client
//   - channel string
func (_e *MockManager_Expecter) SubscribeToChannel(client interface{}, channel interface{}) *MockManager_SubscribeToChannel_Call {
	return &MockManager_SubscribeToChannel_Call{Call: _e.mock.On("SubscribeToChannel", client, channel)}
}

func (_c *MockManager_SubscribeToChannel_Call) Run(run func(client *ws.Client, channel string)) *MockManager_SubscribeToChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ws.Client), args[1].(string))
	})
	return _c
}

func (_c *MockManager_SubscribeToChannel_Call) Return() *MockManager_SubscribeToChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_SubscribeToChannel_Call) RunAndReturn(run func(*ws.Client, string)) *MockManager_SubscribeToChannel_Call {
	_c.Run(run)
	return _c
}

// UnregisterClient provides a mock function with given fields: client
func (_m *MockManager) UnregisterClient(client *ws.Client) {
	_m.Called(client)
}

// MockManager_UnregisterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterClient'
type MockManager_UnregisterClient_Call struct {
	*mock.Call
}

// UnregisterClient is a helper method to define mock.On call
//   - client *ws.Client
func (_e *MockManager_Expecter) UnregisterClient(client interface{}) *MockManager_UnregisterClient_Call {
	return &MockManager_UnregisterClient_Call{Call: _e.mock.On("UnregisterClient", client)}
}

func (_c *MockManager_UnregisterClient_Call) Run(run func(client *ws.Client)) *MockManager_UnregisterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ws.Client))
	})
	return _c
}

func (_c *MockManager_UnregisterClient_Call) Return() *MockManager_UnregisterClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_UnregisterClient_Call) RunAndReturn(run func(*ws.Client)) *MockManager_UnregisterClient_Call {
	_c.Run(run)
	return _c
}

// UnsubscribeFromChannel provides a mock function with given fields: client, channel
func (_m *MockManager) UnsubscribeFromChannel(client *ws.Client, channel string) {
	_m.Called(client, channel)
}

// MockManager_UnsubscribeFromChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsubscribeFromChannel'
type MockManager_UnsubscribeFromChannel_Call struct {
	*mock.Call
}

// UnsubscribeFromChannel is a helper method to define mock.On call
//   - client *ws.Client
//   - channel string
func (_e *MockManager_Expecter) UnsubscribeFromChannel(client interface{}, channel interface{}) *MockManager_UnsubscribeFromChannel_Call {
	return &MockManager_UnsubscribeFromChannel_Call{Call: _e.mock.On("UnsubscribeFromChannel", client, channel)}
}

func (_c *MockManager_UnsubscribeFromChannel_Call) Run(run func(client *ws.Client, channel string)) *MockManager_UnsubscribeFromChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ws.Client), args[1].(string))
	})
	return _c
}

func (_c *MockManager_UnsubscribeFromChannel_Call) Return() *MockManager_UnsubscribeFromChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_UnsubscribeFromChannel_Call) RunAndReturn(run func(*ws.Client, string)) *MockManager_UnsubscribeFromChannel_Call {
	_c.Run(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
