// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocking

import (
	"github.com/Roisfaozi/go-clean-boilerplate/pkg/ws"
	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

func (m *MockManager) Run() {
	m.Called()
}

func (m *MockManager) RegisterClient(client *ws.Client) {
	m.Called(client)
}

func (m *MockManager) UnregisterClient(client *ws.Client) {
	m.Called(client)
}

func (m *MockManager) BroadcastToChannel(channel string, message []byte) {
	m.Called(channel, message)
}

func (m *MockManager) SubscribeToChannel(client *ws.Client, channel string) {
	m.Called(client, channel)
}

func (m *MockManager) UnsubscribeFromChannel(client *ws.Client, channel string) {
	m.Called(client, channel)
}

func (m *MockManager) GetChannelClients(channel string) int {
	args := m.Called(channel)
	return args.Int(0)
}

func (m *MockManager) PresenceUpdate(orgID string, event string, userData *ws.PresenceUser) {
	m.Called(orgID, event, userData)
}

func (m *MockManager) GetPresenceManager() ws.PresenceManager {
	args := m.Called()
	if args.Get(0) == nil {
		return nil
	}
	return args.Get(0).(ws.PresenceManager)
}