// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Roisfaozi/casbin-db/internal/modules/user/model"
	"github.com/Roisfaozi/casbin-db/internal/utils/querybuilder"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserUseCase creates a new instance of MockUserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserUseCase {
	mock := &MockUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserUseCase is an autogenerated mock type for the UserUseCase type
type MockUserUseCase struct {
	mock.Mock
}

type MockUserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUseCase) EXPECT() *MockUserUseCase_Expecter {
	return &MockUserUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) Create(ctx context.Context, request *model.RegisterUserRequest) (*model.UserResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.RegisterUserRequest) (*model.UserResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.RegisterUserRequest) *model.UserResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.RegisterUserRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request *model.RegisterUserRequest
func (_e *MockUserUseCase_Expecter) Create(ctx interface{}, request interface{}) *MockUserUseCase_Create_Call {
	return &MockUserUseCase_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockUserUseCase_Create_Call) Run(run func(ctx context.Context, request *model.RegisterUserRequest)) *MockUserUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.RegisterUserRequest
		if args[1] != nil {
			arg1 = args[1].(*model.RegisterUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_Create_Call) Return(userResponse *model.UserResponse, err error) *MockUserUseCase_Create_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, request *model.RegisterUserRequest) (*model.UserResponse, error)) *MockUserUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Current provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) Current(ctx context.Context, request *model.GetUserRequest) (*model.UserResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 *model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.GetUserRequest) (*model.UserResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.GetUserRequest) *model.UserResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.GetUserRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type MockUserUseCase_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
//   - ctx context.Context
//   - request *model.GetUserRequest
func (_e *MockUserUseCase_Expecter) Current(ctx interface{}, request interface{}) *MockUserUseCase_Current_Call {
	return &MockUserUseCase_Current_Call{Call: _e.mock.On("Current", ctx, request)}
}

func (_c *MockUserUseCase_Current_Call) Run(run func(ctx context.Context, request *model.GetUserRequest)) *MockUserUseCase_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.GetUserRequest
		if args[1] != nil {
			arg1 = args[1].(*model.GetUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_Current_Call) Return(userResponse *model.UserResponse, err error) *MockUserUseCase_Current_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserUseCase_Current_Call) RunAndReturn(run func(ctx context.Context, request *model.GetUserRequest) (*model.UserResponse, error)) *MockUserUseCase_Current_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) DeleteUser(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserUseCase_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserUseCase_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserUseCase_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockUserUseCase_DeleteUser_Call {
	return &MockUserUseCase_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockUserUseCase_DeleteUser_Call) Run(run func(ctx context.Context, id string)) *MockUserUseCase_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_DeleteUser_Call) Return(err error) *MockUserUseCase_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserUseCase_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockUserUseCase_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsers provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) GetAllUsers(ctx context.Context, request *model.GetUserListRequest) ([]*model.UserResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []*model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.GetUserListRequest) ([]*model.UserResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.GetUserListRequest) []*model.UserResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.GetUserListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_GetAllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsers'
type MockUserUseCase_GetAllUsers_Call struct {
	*mock.Call
}

// GetAllUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - request *model.GetUserListRequest
func (_e *MockUserUseCase_Expecter) GetAllUsers(ctx interface{}, request interface{}) *MockUserUseCase_GetAllUsers_Call {
	return &MockUserUseCase_GetAllUsers_Call{Call: _e.mock.On("GetAllUsers", ctx, request)}
}

func (_c *MockUserUseCase_GetAllUsers_Call) Run(run func(ctx context.Context, request *model.GetUserListRequest)) *MockUserUseCase_GetAllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.GetUserListRequest
		if args[1] != nil {
			arg1 = args[1].(*model.GetUserListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_GetAllUsers_Call) Return(userResponses []*model.UserResponse, err error) *MockUserUseCase_GetAllUsers_Call {
	_c.Call.Return(userResponses, err)
	return _c
}

func (_c *MockUserUseCase_GetAllUsers_Call) RunAndReturn(run func(ctx context.Context, request *model.GetUserListRequest) ([]*model.UserResponse, error)) *MockUserUseCase_GetAllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsersDynamic provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) GetAllUsersDynamic(ctx context.Context, filter *querybuilder.DynamicFilter) ([]*model.UserResponse, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsersDynamic")
	}

	var r0 []*model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) ([]*model.UserResponse, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) []*model.UserResponse); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *querybuilder.DynamicFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_GetAllUsersDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsersDynamic'
type MockUserUseCase_GetAllUsersDynamic_Call struct {
	*mock.Call
}

// GetAllUsersDynamic is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *querybuilder.DynamicFilter
func (_e *MockUserUseCase_Expecter) GetAllUsersDynamic(ctx interface{}, filter interface{}) *MockUserUseCase_GetAllUsersDynamic_Call {
	return &MockUserUseCase_GetAllUsersDynamic_Call{Call: _e.mock.On("GetAllUsersDynamic", ctx, filter)}
}

func (_c *MockUserUseCase_GetAllUsersDynamic_Call) Run(run func(ctx context.Context, filter *querybuilder.DynamicFilter)) *MockUserUseCase_GetAllUsersDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *querybuilder.DynamicFilter
		if args[1] != nil {
			arg1 = args[1].(*querybuilder.DynamicFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_GetAllUsersDynamic_Call) Return(userResponses []*model.UserResponse, err error) *MockUserUseCase_GetAllUsersDynamic_Call {
	_c.Call.Return(userResponses, err)
	return _c
}

func (_c *MockUserUseCase_GetAllUsersDynamic_Call) RunAndReturn(run func(ctx context.Context, filter *querybuilder.DynamicFilter) ([]*model.UserResponse, error)) *MockUserUseCase_GetAllUsersDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) GetUserByID(ctx context.Context, id string) (*model.UserResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.UserResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.UserResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserUseCase_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserUseCase_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserUseCase_GetUserByID_Call {
	return &MockUserUseCase_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserUseCase_GetUserByID_Call) Run(run func(ctx context.Context, id string)) *MockUserUseCase_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_GetUserByID_Call) Return(userResponse *model.UserResponse, err error) *MockUserUseCase_GetUserByID_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserUseCase_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.UserResponse, error)) *MockUserUseCase_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserUseCase
func (_mock *MockUserUseCase) Update(ctx context.Context, request *model.UpdateUserRequest) (*model.UserResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UpdateUserRequest) (*model.UserResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.UpdateUserRequest) *model.UserResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.UpdateUserRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUseCase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserUseCase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - request *model.UpdateUserRequest
func (_e *MockUserUseCase_Expecter) Update(ctx interface{}, request interface{}) *MockUserUseCase_Update_Call {
	return &MockUserUseCase_Update_Call{Call: _e.mock.On("Update", ctx, request)}
}

func (_c *MockUserUseCase_Update_Call) Run(run func(ctx context.Context, request *model.UpdateUserRequest)) *MockUserUseCase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.UpdateUserRequest
		if args[1] != nil {
			arg1 = args[1].(*model.UpdateUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUseCase_Update_Call) Return(userResponse *model.UserResponse, err error) *MockUserUseCase_Update_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *MockUserUseCase_Update_Call) RunAndReturn(run func(ctx context.Context, request *model.UpdateUserRequest) (*model.UserResponse, error)) *MockUserUseCase_Update_Call {
	_c.Call.Return(run)
	return _c
}
