// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Roisfaozi/casbin-db/internal/modules/user/model"
	mock "github.com/stretchr/testify/mock"
)

// MockUserUseCase is an autogenerated mocking type for the MockUserUseCase type
type MockUserUseCase struct {
	mock.Mock
}

// Register provides a mocking function with given fields: ctx, request
func (_m *MockUserUseCase) Register(ctx context.Context, request model.RegisterUserRequest) (*model.UserResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 *model.UserResponse
	if rf, ok := ret.Get(0).(func(context.Context, model.RegisterUserRequest) *model.UserResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.RegisterUserRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mocking function with given fields: ctx, request
func (_m *MockUserUseCase) Login(ctx context.Context, request model.LoginUserRequest) (*model.UserResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 *model.UserResponse
	if rf, ok := ret.Get(0).(func(context.Context, model.LoginUserRequest) *model.UserResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.LoginUserRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mocking function with given fields: ctx, id
func (_m *MockUserUseCase) GetByID(ctx context.Context, id string) (*model.UserResponse, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.UserResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mocking function with given fields: ctx, id, request
func (_m *MockUserUseCase) Update(ctx context.Context, id string, request model.UpdateUserRequest) (*model.UserResponse, error) {
	ret := _m.Called(ctx, id, request)

	var r0 *model.UserResponse
	if rf, ok := ret.Get(0).(func(context.Context, string, model.UpdateUserRequest) *model.UserResponse); ok {
		r0 = rf(ctx, id, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, model.UpdateUserRequest) error); ok {
		r1 = rf(ctx, id, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mocking function with given fields: ctx, id
func (_m *MockUserUseCase) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mocking function with given fields: ctx, limit, offset
func (_m *MockUserUseCase) GetAll(ctx context.Context, limit int, offset int) ([]*model.UserResponse, error) {
	ret := _m.Called(ctx, limit, offset)

	var r0 []*model.UserResponse
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*model.UserResponse); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyToken provides a mocking function with given fields: ctx, token
func (_m *MockUserUseCase) VerifyToken(ctx context.Context, token string) (*model.UserResponse, error) {
	ret := _m.Called(ctx, token)

	var r0 *model.UserResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserResponse); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserUseCase creates a new instance of MockUserUseCase. It also registers a testing interface on the mocking and a cleanup function to assert the mocking expectations.
func NewUserUseCase(t mockConstructorTestingTNewUserUseCase) *MockUserUseCase {
	mock := &MockUserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
