// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/auth/model"
	mock "github.com/stretchr/testify/mock"
)

// MockNotificationPublisher is an autogenerated mock type for the NotificationPublisher type
type MockNotificationPublisher struct {
	mock.Mock
}

type MockNotificationPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationPublisher) EXPECT() *MockNotificationPublisher_Expecter {
	return &MockNotificationPublisher_Expecter{mock: &_m.Mock}
}

// PublishUserLoggedIn provides a mock function with given fields: ctx, user, orgIDs
func (_m *MockNotificationPublisher) PublishUserLoggedIn(ctx context.Context, user model.UserInfo, orgIDs []string) {
	_m.Called(ctx, user, orgIDs)
}

// MockNotificationPublisher_PublishUserLoggedIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserLoggedIn'
type MockNotificationPublisher_PublishUserLoggedIn_Call struct {
	*mock.Call
}

// PublishUserLoggedIn is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.UserInfo
//   - orgIDs []string
func (_e *MockNotificationPublisher_Expecter) PublishUserLoggedIn(ctx interface{}, user interface{}, orgIDs interface{}) *MockNotificationPublisher_PublishUserLoggedIn_Call {
	return &MockNotificationPublisher_PublishUserLoggedIn_Call{Call: _e.mock.On("PublishUserLoggedIn", ctx, user, orgIDs)}
}

func (_c *MockNotificationPublisher_PublishUserLoggedIn_Call) Run(run func(ctx context.Context, user model.UserInfo, orgIDs []string)) *MockNotificationPublisher_PublishUserLoggedIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.UserInfo), args[2].([]string))
	})
	return _c
}

func (_c *MockNotificationPublisher_PublishUserLoggedIn_Call) Return() *MockNotificationPublisher_PublishUserLoggedIn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotificationPublisher_PublishUserLoggedIn_Call) RunAndReturn(run func(context.Context, model.UserInfo, []string)) *MockNotificationPublisher_PublishUserLoggedIn_Call {
	_c.Run(run)
	return _c
}

// NewMockNotificationPublisher creates a new instance of MockNotificationPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationPublisher {
	mock := &MockNotificationPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
