// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/webhook/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockWebhookRepository is an autogenerated mock type for the WebhookRepository type
type MockWebhookRepository struct {
	mock.Mock
}

type MockWebhookRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebhookRepository) EXPECT() *MockWebhookRepository_Expecter {
	return &MockWebhookRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, webhook
func (_m *MockWebhookRepository) Create(ctx context.Context, webhook *entity.Webhook) error {
	ret := _m.Called(ctx, webhook)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Webhook) error); ok {
		r0 = rf(ctx, webhook)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebhookRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWebhookRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - webhook *entity.Webhook
func (_e *MockWebhookRepository_Expecter) Create(ctx interface{}, webhook interface{}) *MockWebhookRepository_Create_Call {
	return &MockWebhookRepository_Create_Call{Call: _e.mock.On("Create", ctx, webhook)}
}

func (_c *MockWebhookRepository_Create_Call) Run(run func(ctx context.Context, webhook *entity.Webhook)) *MockWebhookRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Webhook))
	})
	return _c
}

func (_c *MockWebhookRepository_Create_Call) Return(_a0 error) *MockWebhookRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Webhook) error) *MockWebhookRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLog provides a mock function with given fields: ctx, log
func (_m *MockWebhookRepository) CreateLog(ctx context.Context, log *entity.WebhookLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for CreateLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.WebhookLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebhookRepository_CreateLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLog'
type MockWebhookRepository_CreateLog_Call struct {
	*mock.Call
}

// CreateLog is a helper method to define mock.On call
//   - ctx context.Context
//   - log *entity.WebhookLog
func (_e *MockWebhookRepository_Expecter) CreateLog(ctx interface{}, log interface{}) *MockWebhookRepository_CreateLog_Call {
	return &MockWebhookRepository_CreateLog_Call{Call: _e.mock.On("CreateLog", ctx, log)}
}

func (_c *MockWebhookRepository_CreateLog_Call) Run(run func(ctx context.Context, log *entity.WebhookLog)) *MockWebhookRepository_CreateLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.WebhookLog))
	})
	return _c
}

func (_c *MockWebhookRepository_CreateLog_Call) Return(_a0 error) *MockWebhookRepository_CreateLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookRepository_CreateLog_Call) RunAndReturn(run func(context.Context, *entity.WebhookLog) error) *MockWebhookRepository_CreateLog_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, organizationID
func (_m *MockWebhookRepository) Delete(ctx context.Context, id string, organizationID string) error {
	ret := _m.Called(ctx, id, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, organizationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebhookRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWebhookRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - organizationID string
func (_e *MockWebhookRepository_Expecter) Delete(ctx interface{}, id interface{}, organizationID interface{}) *MockWebhookRepository_Delete_Call {
	return &MockWebhookRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id, organizationID)}
}

func (_c *MockWebhookRepository_Delete_Call) Run(run func(ctx context.Context, id string, organizationID string)) *MockWebhookRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockWebhookRepository_Delete_Call) Return(_a0 error) *MockWebhookRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockWebhookRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEvent provides a mock function with given fields: ctx, organizationID, event
func (_m *MockWebhookRepository) FindByEvent(ctx context.Context, organizationID string, event string) ([]entity.Webhook, error) {
	ret := _m.Called(ctx, organizationID, event)

	if len(ret) == 0 {
		panic("no return value specified for FindByEvent")
	}

	var r0 []entity.Webhook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]entity.Webhook, error)); ok {
		return rf(ctx, organizationID, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []entity.Webhook); ok {
		r0 = rf(ctx, organizationID, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Webhook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, organizationID, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebhookRepository_FindByEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEvent'
type MockWebhookRepository_FindByEvent_Call struct {
	*mock.Call
}

// FindByEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
//   - event string
func (_e *MockWebhookRepository_Expecter) FindByEvent(ctx interface{}, organizationID interface{}, event interface{}) *MockWebhookRepository_FindByEvent_Call {
	return &MockWebhookRepository_FindByEvent_Call{Call: _e.mock.On("FindByEvent", ctx, organizationID, event)}
}

func (_c *MockWebhookRepository_FindByEvent_Call) Run(run func(ctx context.Context, organizationID string, event string)) *MockWebhookRepository_FindByEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockWebhookRepository_FindByEvent_Call) Return(_a0 []entity.Webhook, _a1 error) *MockWebhookRepository_FindByEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebhookRepository_FindByEvent_Call) RunAndReturn(run func(context.Context, string, string) ([]entity.Webhook, error)) *MockWebhookRepository_FindByEvent_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id, organizationID
func (_m *MockWebhookRepository) FindByID(ctx context.Context, id string, organizationID string) (*entity.Webhook, error) {
	ret := _m.Called(ctx, id, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Webhook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entity.Webhook, error)); ok {
		return rf(ctx, id, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.Webhook); ok {
		r0 = rf(ctx, id, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Webhook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebhookRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockWebhookRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - organizationID string
func (_e *MockWebhookRepository_Expecter) FindByID(ctx interface{}, id interface{}, organizationID interface{}) *MockWebhookRepository_FindByID_Call {
	return &MockWebhookRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id, organizationID)}
}

func (_c *MockWebhookRepository_FindByID_Call) Run(run func(ctx context.Context, id string, organizationID string)) *MockWebhookRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockWebhookRepository_FindByID_Call) Return(_a0 *entity.Webhook, _a1 error) *MockWebhookRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebhookRepository_FindByID_Call) RunAndReturn(run func(context.Context, string, string) (*entity.Webhook, error)) *MockWebhookRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOrganizationID provides a mock function with given fields: ctx, organizationID
func (_m *MockWebhookRepository) FindByOrganizationID(ctx context.Context, organizationID string) ([]entity.Webhook, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrganizationID")
	}

	var r0 []entity.Webhook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.Webhook, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.Webhook); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Webhook)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebhookRepository_FindByOrganizationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrganizationID'
type MockWebhookRepository_FindByOrganizationID_Call struct {
	*mock.Call
}

// FindByOrganizationID is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID string
func (_e *MockWebhookRepository_Expecter) FindByOrganizationID(ctx interface{}, organizationID interface{}) *MockWebhookRepository_FindByOrganizationID_Call {
	return &MockWebhookRepository_FindByOrganizationID_Call{Call: _e.mock.On("FindByOrganizationID", ctx, organizationID)}
}

func (_c *MockWebhookRepository_FindByOrganizationID_Call) Run(run func(ctx context.Context, organizationID string)) *MockWebhookRepository_FindByOrganizationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWebhookRepository_FindByOrganizationID_Call) Return(_a0 []entity.Webhook, _a1 error) *MockWebhookRepository_FindByOrganizationID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebhookRepository_FindByOrganizationID_Call) RunAndReturn(run func(context.Context, string) ([]entity.Webhook, error)) *MockWebhookRepository_FindByOrganizationID_Call {
	_c.Call.Return(run)
	return _c
}

// FindLogsByWebhookID provides a mock function with given fields: ctx, webhookID, limit, offset
func (_m *MockWebhookRepository) FindLogsByWebhookID(ctx context.Context, webhookID string, limit int, offset int) ([]entity.WebhookLog, error) {
	ret := _m.Called(ctx, webhookID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindLogsByWebhookID")
	}

	var r0 []entity.WebhookLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]entity.WebhookLog, error)); ok {
		return rf(ctx, webhookID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []entity.WebhookLog); ok {
		r0 = rf(ctx, webhookID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.WebhookLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, webhookID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWebhookRepository_FindLogsByWebhookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLogsByWebhookID'
type MockWebhookRepository_FindLogsByWebhookID_Call struct {
	*mock.Call
}

// FindLogsByWebhookID is a helper method to define mock.On call
//   - ctx context.Context
//   - webhookID string
//   - limit int
//   - offset int
func (_e *MockWebhookRepository_Expecter) FindLogsByWebhookID(ctx interface{}, webhookID interface{}, limit interface{}, offset interface{}) *MockWebhookRepository_FindLogsByWebhookID_Call {
	return &MockWebhookRepository_FindLogsByWebhookID_Call{Call: _e.mock.On("FindLogsByWebhookID", ctx, webhookID, limit, offset)}
}

func (_c *MockWebhookRepository_FindLogsByWebhookID_Call) Run(run func(ctx context.Context, webhookID string, limit int, offset int)) *MockWebhookRepository_FindLogsByWebhookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockWebhookRepository_FindLogsByWebhookID_Call) Return(_a0 []entity.WebhookLog, _a1 error) *MockWebhookRepository_FindLogsByWebhookID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWebhookRepository_FindLogsByWebhookID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]entity.WebhookLog, error)) *MockWebhookRepository_FindLogsByWebhookID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, webhook
func (_m *MockWebhookRepository) Update(ctx context.Context, webhook *entity.Webhook) error {
	ret := _m.Called(ctx, webhook)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Webhook) error); ok {
		r0 = rf(ctx, webhook)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebhookRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWebhookRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - webhook *entity.Webhook
func (_e *MockWebhookRepository_Expecter) Update(ctx interface{}, webhook interface{}) *MockWebhookRepository_Update_Call {
	return &MockWebhookRepository_Update_Call{Call: _e.mock.On("Update", ctx, webhook)}
}

func (_c *MockWebhookRepository_Update_Call) Run(run func(ctx context.Context, webhook *entity.Webhook)) *MockWebhookRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Webhook))
	})
	return _c
}

func (_c *MockWebhookRepository_Update_Call) Return(_a0 error) *MockWebhookRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebhookRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Webhook) error) *MockWebhookRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebhookRepository creates a new instance of MockWebhookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebhookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebhookRepository {
	mock := &MockWebhookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
