import { NextRequest, NextResponse } from "next/server";

export const runtime = "edge";

/**
 * Dummy AI Chat API for local UI development.
 * Simulates a streaming response word by word.
 */
export async function POST(req: NextRequest) {
  try {
    const { messages } = await req.json();
    const lastMessage = messages[messages.length - 1]?.content || "Hello!";

    const responseText = `I'm a dummy NexusAI assistant. You asked: "${lastMessage}". In a real implementation, this response would be generated by an LLM on the Go backend and streamed back to you. I can analyze your audit logs, manage users, and help you configure Casbin policies.`;

    const words = responseText.split(" ");
    const encoder = new TextEncoder();

    const stream = new ReadableStream({
      async start(controller) {
        for (const word of words) {
          // Add a small delay to simulate thinking/generation
          await new Promise((resolve) => setTimeout(resolve, 100));
          const payload = JSON.stringify({ text: word + " " });
          controller.enqueue(encoder.encode(`data: ${payload}\n\n`));
        }
        controller.enqueue(encoder.encode("event: finish\ndata: {}\n\n"));
        controller.close();
      },
    });

    return new Response(stream, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
      },
    });
  } catch (error) {
    return NextResponse.json(
      { error: "Failed to process request" },
      { status: 500 }
    );
  }
}
