// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/api_key/model"
	mock "github.com/stretchr/testify/mock"
)

// MockApiKeyUseCase is an autogenerated mock type for the ApiKeyUseCase type
type MockApiKeyUseCase struct {
	mock.Mock
}

type MockApiKeyUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApiKeyUseCase) EXPECT() *MockApiKeyUseCase_Expecter {
	return &MockApiKeyUseCase_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, key
func (_m *MockApiKeyUseCase) Authenticate(ctx context.Context, key string) (*model.ApiKeyIdentity, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *model.ApiKeyIdentity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.ApiKeyIdentity, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.ApiKeyIdentity); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ApiKeyIdentity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApiKeyUseCase_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockApiKeyUseCase_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockApiKeyUseCase_Expecter) Authenticate(ctx interface{}, key interface{}) *MockApiKeyUseCase_Authenticate_Call {
	return &MockApiKeyUseCase_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, key)}
}

func (_c *MockApiKeyUseCase_Authenticate_Call) Run(run func(ctx context.Context, key string)) *MockApiKeyUseCase_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockApiKeyUseCase_Authenticate_Call) Return(_a0 *model.ApiKeyIdentity, _a1 error) *MockApiKeyUseCase_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApiKeyUseCase_Authenticate_Call) RunAndReturn(run func(context.Context, string) (*model.ApiKeyIdentity, error)) *MockApiKeyUseCase_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, userID, orgID, req
func (_m *MockApiKeyUseCase) Create(ctx context.Context, userID string, orgID string, req *model.CreateApiKeyRequest) (*model.CreateApiKeyResponse, error) {
	ret := _m.Called(ctx, userID, orgID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.CreateApiKeyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.CreateApiKeyRequest) (*model.CreateApiKeyResponse, error)); ok {
		return rf(ctx, userID, orgID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *model.CreateApiKeyRequest) *model.CreateApiKeyResponse); ok {
		r0 = rf(ctx, userID, orgID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CreateApiKeyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *model.CreateApiKeyRequest) error); ok {
		r1 = rf(ctx, userID, orgID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApiKeyUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockApiKeyUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - orgID string
//   - req *model.CreateApiKeyRequest
func (_e *MockApiKeyUseCase_Expecter) Create(ctx interface{}, userID interface{}, orgID interface{}, req interface{}) *MockApiKeyUseCase_Create_Call {
	return &MockApiKeyUseCase_Create_Call{Call: _e.mock.On("Create", ctx, userID, orgID, req)}
}

func (_c *MockApiKeyUseCase_Create_Call) Run(run func(ctx context.Context, userID string, orgID string, req *model.CreateApiKeyRequest)) *MockApiKeyUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*model.CreateApiKeyRequest))
	})
	return _c
}

func (_c *MockApiKeyUseCase_Create_Call) Return(_a0 *model.CreateApiKeyResponse, _a1 error) *MockApiKeyUseCase_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApiKeyUseCase_Create_Call) RunAndReturn(run func(context.Context, string, string, *model.CreateApiKeyRequest) (*model.CreateApiKeyResponse, error)) *MockApiKeyUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orgID
func (_m *MockApiKeyUseCase) List(ctx context.Context, orgID string) ([]model.ApiKeyResponse, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.ApiKeyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.ApiKeyResponse, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.ApiKeyResponse); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ApiKeyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApiKeyUseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockApiKeyUseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
func (_e *MockApiKeyUseCase_Expecter) List(ctx interface{}, orgID interface{}) *MockApiKeyUseCase_List_Call {
	return &MockApiKeyUseCase_List_Call{Call: _e.mock.On("List", ctx, orgID)}
}

func (_c *MockApiKeyUseCase_List_Call) Run(run func(ctx context.Context, orgID string)) *MockApiKeyUseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockApiKeyUseCase_List_Call) Return(_a0 []model.ApiKeyResponse, _a1 error) *MockApiKeyUseCase_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApiKeyUseCase_List_Call) RunAndReturn(run func(context.Context, string) ([]model.ApiKeyResponse, error)) *MockApiKeyUseCase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, orgID, id
func (_m *MockApiKeyUseCase) Revoke(ctx context.Context, orgID string, id string) error {
	ret := _m.Called(ctx, orgID, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orgID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApiKeyUseCase_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockApiKeyUseCase_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID string
//   - id string
func (_e *MockApiKeyUseCase_Expecter) Revoke(ctx interface{}, orgID interface{}, id interface{}) *MockApiKeyUseCase_Revoke_Call {
	return &MockApiKeyUseCase_Revoke_Call{Call: _e.mock.On("Revoke", ctx, orgID, id)}
}

func (_c *MockApiKeyUseCase_Revoke_Call) Run(run func(ctx context.Context, orgID string, id string)) *MockApiKeyUseCase_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockApiKeyUseCase_Revoke_Call) Return(_a0 error) *MockApiKeyUseCase_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApiKeyUseCase_Revoke_Call) RunAndReturn(run func(context.Context, string, string) error) *MockApiKeyUseCase_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApiKeyUseCase creates a new instance of MockApiKeyUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApiKeyUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApiKeyUseCase {
	mock := &MockApiKeyUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
