// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	asynq "github.com/hibiken/asynq"

	mock "github.com/stretchr/testify/mock"

	model "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/audit/model"
)

// MockTaskDistributor is an autogenerated mock type for the TaskDistributor type
type MockTaskDistributor struct {
	mock.Mock
}

type MockTaskDistributor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskDistributor) EXPECT() *MockTaskDistributor_Expecter {
	return &MockTaskDistributor_Expecter{mock: &_m.Mock}
}

// DistributeTaskAuditLogExport provides a mock function with given fields: ctx, payload, opts
func (_m *MockTaskDistributor) DistributeTaskAuditLogExport(ctx context.Context, payload model.AuditLogExportPayload, opts ...asynq.Option) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, payload)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DistributeTaskAuditLogExport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AuditLogExportPayload, ...asynq.Option) error); ok {
		r0 = rf(ctx, payload, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskDistributor_DistributeTaskAuditLogExport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DistributeTaskAuditLogExport'
type MockTaskDistributor_DistributeTaskAuditLogExport_Call struct {
	*mock.Call
}

// DistributeTaskAuditLogExport is a helper method to define mock.On call
//   - ctx context.Context
//   - payload model.AuditLogExportPayload
//   - opts ...asynq.Option
func (_e *MockTaskDistributor_Expecter) DistributeTaskAuditLogExport(ctx interface{}, payload interface{}, opts ...interface{}) *MockTaskDistributor_DistributeTaskAuditLogExport_Call {
	return &MockTaskDistributor_DistributeTaskAuditLogExport_Call{Call: _e.mock.On("DistributeTaskAuditLogExport",
		append([]interface{}{ctx, payload}, opts...)...)}
}

func (_c *MockTaskDistributor_DistributeTaskAuditLogExport_Call) Run(run func(ctx context.Context, payload model.AuditLogExportPayload, opts ...asynq.Option)) *MockTaskDistributor_DistributeTaskAuditLogExport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]asynq.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(asynq.Option)
			}
		}
		run(args[0].(context.Context), args[1].(model.AuditLogExportPayload), variadicArgs...)
	})
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskAuditLogExport_Call) Return(_a0 error) *MockTaskDistributor_DistributeTaskAuditLogExport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskDistributor_DistributeTaskAuditLogExport_Call) RunAndReturn(run func(context.Context, model.AuditLogExportPayload, ...asynq.Option) error) *MockTaskDistributor_DistributeTaskAuditLogExport_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskDistributor creates a new instance of MockTaskDistributor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskDistributor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskDistributor {
	mock := &MockTaskDistributor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
