// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Roisfaozi/go-clean-boilerplate/internal/modules/audit/entity"
	"github.com/Roisfaozi/go-clean-boilerplate/internal/modules/audit/model"
	"github.com/Roisfaozi/go-clean-boilerplate/pkg/querybuilder"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuditRepository creates a new instance of MockAuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditRepository {
	mock := &MockAuditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditRepository is an autogenerated mock type for the AuditRepository type
type MockAuditRepository struct {
	mock.Mock
}

type MockAuditRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditRepository) EXPECT() *MockAuditRepository_Expecter {
	return &MockAuditRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) Create(ctx context.Context, log *entity.AuditLog) error {
	ret := _mock.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.AuditLog) error); ok {
		r0 = returnFunc(ctx, log)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - log *entity.AuditLog
func (_e *MockAuditRepository_Expecter) Create(ctx interface{}, log interface{}) *MockAuditRepository_Create_Call {
	return &MockAuditRepository_Create_Call{Call: _e.mock.On("Create", ctx, log)}
}

func (_c *MockAuditRepository_Create_Call) Run(run func(ctx context.Context, log *entity.AuditLog)) *MockAuditRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.AuditLog
		if args[1] != nil {
			arg1 = args[1].(*entity.AuditLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditRepository_Create_Call) Return(err error) *MockAuditRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditRepository_Create_Call) RunAndReturn(run func(ctx context.Context, log *entity.AuditLog) error) *MockAuditRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLogsOlderThan provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) DeleteLogsOlderThan(ctx context.Context, cutoffTime int64) error {
	ret := _mock.Called(ctx, cutoffTime)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLogsOlderThan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, cutoffTime)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditRepository_DeleteLogsOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLogsOlderThan'
type MockAuditRepository_DeleteLogsOlderThan_Call struct {
	*mock.Call
}

// DeleteLogsOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoffTime int64
func (_e *MockAuditRepository_Expecter) DeleteLogsOlderThan(ctx interface{}, cutoffTime interface{}) *MockAuditRepository_DeleteLogsOlderThan_Call {
	return &MockAuditRepository_DeleteLogsOlderThan_Call{Call: _e.mock.On("DeleteLogsOlderThan", ctx, cutoffTime)}
}

func (_c *MockAuditRepository_DeleteLogsOlderThan_Call) Run(run func(ctx context.Context, cutoffTime int64)) *MockAuditRepository_DeleteLogsOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditRepository_DeleteLogsOlderThan_Call) Return(err error) *MockAuditRepository_DeleteLogsOlderThan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditRepository_DeleteLogsOlderThan_Call) RunAndReturn(run func(ctx context.Context, cutoffTime int64) error) *MockAuditRepository_DeleteLogsOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllDynamic provides a mock function for the type MockAuditRepository
func (_mock *MockAuditRepository) FindAllDynamic(ctx context.Context, filter *querybuilder.DynamicFilter) ([]*entity.AuditLog, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAllDynamic")
	}

	var r0 []*entity.AuditLog
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) ([]*entity.AuditLog, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) []*entity.AuditLog); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AuditLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *querybuilder.DynamicFilter) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *querybuilder.DynamicFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuditRepository_FindAllDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllDynamic'
type MockAuditRepository_FindAllDynamic_Call struct {
	*mock.Call
}

// FindAllDynamic is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *querybuilder.DynamicFilter
func (_e *MockAuditRepository_Expecter) FindAllDynamic(ctx interface{}, filter interface{}) *MockAuditRepository_FindAllDynamic_Call {
	return &MockAuditRepository_FindAllDynamic_Call{Call: _e.mock.On("FindAllDynamic", ctx, filter)}
}

func (_c *MockAuditRepository_FindAllDynamic_Call) Run(run func(ctx context.Context, filter *querybuilder.DynamicFilter)) *MockAuditRepository_FindAllDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *querybuilder.DynamicFilter
		if args[1] != nil {
			arg1 = args[1].(*querybuilder.DynamicFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditRepository_FindAllDynamic_Call) Return(auditLogs []*entity.AuditLog, n int64, err error) *MockAuditRepository_FindAllDynamic_Call {
	_c.Call.Return(auditLogs, n, err)
	return _c
}

func (_c *MockAuditRepository_FindAllDynamic_Call) RunAndReturn(run func(ctx context.Context, filter *querybuilder.DynamicFilter) ([]*entity.AuditLog, int64, error)) *MockAuditRepository_FindAllDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditUseCase creates a new instance of MockAuditUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditUseCase {
	mock := &MockAuditUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditUseCase is an autogenerated mock type for the AuditUseCase type
type MockAuditUseCase struct {
	mock.Mock
}

type MockAuditUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditUseCase) EXPECT() *MockAuditUseCase_Expecter {
	return &MockAuditUseCase_Expecter{mock: &_m.Mock}
}

// GetLogsDynamic provides a mock function for the type MockAuditUseCase
func (_mock *MockAuditUseCase) GetLogsDynamic(ctx context.Context, filter *querybuilder.DynamicFilter) ([]model.AuditLogResponse, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetLogsDynamic")
	}

	var r0 []model.AuditLogResponse
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) ([]model.AuditLogResponse, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) []model.AuditLogResponse); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AuditLogResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *querybuilder.DynamicFilter) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *querybuilder.DynamicFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuditUseCase_GetLogsDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogsDynamic'
type MockAuditUseCase_GetLogsDynamic_Call struct {
	*mock.Call
}

// GetLogsDynamic is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *querybuilder.DynamicFilter
func (_e *MockAuditUseCase_Expecter) GetLogsDynamic(ctx interface{}, filter interface{}) *MockAuditUseCase_GetLogsDynamic_Call {
	return &MockAuditUseCase_GetLogsDynamic_Call{Call: _e.mock.On("GetLogsDynamic", ctx, filter)}
}

func (_c *MockAuditUseCase_GetLogsDynamic_Call) Run(run func(ctx context.Context, filter *querybuilder.DynamicFilter)) *MockAuditUseCase_GetLogsDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *querybuilder.DynamicFilter
		if args[1] != nil {
			arg1 = args[1].(*querybuilder.DynamicFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditUseCase_GetLogsDynamic_Call) Return(auditLogResponses []model.AuditLogResponse, n int64, err error) *MockAuditUseCase_GetLogsDynamic_Call {
	_c.Call.Return(auditLogResponses, n, err)
	return _c
}

func (_c *MockAuditUseCase_GetLogsDynamic_Call) RunAndReturn(run func(ctx context.Context, filter *querybuilder.DynamicFilter) ([]model.AuditLogResponse, int64, error)) *MockAuditUseCase_GetLogsDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// LogActivity provides a mock function for the type MockAuditUseCase
func (_mock *MockAuditUseCase) LogActivity(ctx context.Context, req model.CreateAuditLogRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for LogActivity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateAuditLogRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditUseCase_LogActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogActivity'
type MockAuditUseCase_LogActivity_Call struct {
	*mock.Call
}

// LogActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.CreateAuditLogRequest
func (_e *MockAuditUseCase_Expecter) LogActivity(ctx interface{}, req interface{}) *MockAuditUseCase_LogActivity_Call {
	return &MockAuditUseCase_LogActivity_Call{Call: _e.mock.On("LogActivity", ctx, req)}
}

func (_c *MockAuditUseCase_LogActivity_Call) Run(run func(ctx context.Context, req model.CreateAuditLogRequest)) *MockAuditUseCase_LogActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.CreateAuditLogRequest
		if args[1] != nil {
			arg1 = args[1].(model.CreateAuditLogRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditUseCase_LogActivity_Call) Return(err error) *MockAuditUseCase_LogActivity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditUseCase_LogActivity_Call) RunAndReturn(run func(ctx context.Context, req model.CreateAuditLogRequest) error) *MockAuditUseCase_LogActivity_Call {
	_c.Call.Return(run)
	return _c
}
