// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/Roisfaozi/go-clean-boilerplate/internal/modules/audit/model"
	querybuilder "github.com/Roisfaozi/go-clean-boilerplate/pkg/querybuilder"
	mock "github.com/stretchr/testify/mock"
)

// MockAuditUseCase is an autogenerated mock type for the AuditUseCase type
type MockAuditUseCase struct {
	mock.Mock
}

type MockAuditUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditUseCase) EXPECT() *MockAuditUseCase_Expecter {
	return &MockAuditUseCase_Expecter{mock: &_m.Mock}
}

// ExportLogs provides a mock function with given fields: ctx, fromDate, toDate, process
func (_m *MockAuditUseCase) ExportLogs(ctx context.Context, fromDate string, toDate string, process func([]model.AuditLogResponse) error) error {
	ret := _m.Called(ctx, fromDate, toDate, process)

	if len(ret) == 0 {
		panic("no return value specified for ExportLogs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, func([]model.AuditLogResponse) error) error); ok {
		r0 = rf(ctx, fromDate, toDate, process)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditUseCase_ExportLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportLogs'
type MockAuditUseCase_ExportLogs_Call struct {
	*mock.Call
}

// ExportLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - fromDate string
//   - toDate string
//   - process func([]model.AuditLogResponse) error
func (_e *MockAuditUseCase_Expecter) ExportLogs(ctx interface{}, fromDate interface{}, toDate interface{}, process interface{}) *MockAuditUseCase_ExportLogs_Call {
	return &MockAuditUseCase_ExportLogs_Call{Call: _e.mock.On("ExportLogs", ctx, fromDate, toDate, process)}
}

func (_c *MockAuditUseCase_ExportLogs_Call) Run(run func(ctx context.Context, fromDate string, toDate string, process func([]model.AuditLogResponse) error)) *MockAuditUseCase_ExportLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(func([]model.AuditLogResponse) error))
	})
	return _c
}

func (_c *MockAuditUseCase_ExportLogs_Call) Return(_a0 error) *MockAuditUseCase_ExportLogs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditUseCase_ExportLogs_Call) RunAndReturn(run func(context.Context, string, string, func([]model.AuditLogResponse) error) error) *MockAuditUseCase_ExportLogs_Call {
	_c.Call.Return(run)
	return _c
}

// ExportLogsAsync provides a mock function with given fields: ctx, userID, orgID, fromDate, toDate, format
func (_m *MockAuditUseCase) ExportLogsAsync(ctx context.Context, userID string, orgID string, fromDate string, toDate string, format string) error {
	ret := _m.Called(ctx, userID, orgID, fromDate, toDate, format)

	if len(ret) == 0 {
		panic("no return value specified for ExportLogsAsync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) error); ok {
		r0 = rf(ctx, userID, orgID, fromDate, toDate, format)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditUseCase_ExportLogsAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportLogsAsync'
type MockAuditUseCase_ExportLogsAsync_Call struct {
	*mock.Call
}

// ExportLogsAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - orgID string
//   - fromDate string
//   - toDate string
//   - format string
func (_e *MockAuditUseCase_Expecter) ExportLogsAsync(ctx interface{}, userID interface{}, orgID interface{}, fromDate interface{}, toDate interface{}, format interface{}) *MockAuditUseCase_ExportLogsAsync_Call {
	return &MockAuditUseCase_ExportLogsAsync_Call{Call: _e.mock.On("ExportLogsAsync", ctx, userID, orgID, fromDate, toDate, format)}
}

func (_c *MockAuditUseCase_ExportLogsAsync_Call) Run(run func(ctx context.Context, userID string, orgID string, fromDate string, toDate string, format string)) *MockAuditUseCase_ExportLogsAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockAuditUseCase_ExportLogsAsync_Call) Return(_a0 error) *MockAuditUseCase_ExportLogsAsync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditUseCase_ExportLogsAsync_Call) RunAndReturn(run func(context.Context, string, string, string, string, string) error) *MockAuditUseCase_ExportLogsAsync_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogsDynamic provides a mock function with given fields: ctx, filter
func (_m *MockAuditUseCase) GetLogsDynamic(ctx context.Context, filter *querybuilder.DynamicFilter) ([]model.AuditLogResponse, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetLogsDynamic")
	}

	var r0 []model.AuditLogResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) ([]model.AuditLogResponse, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *querybuilder.DynamicFilter) []model.AuditLogResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AuditLogResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *querybuilder.DynamicFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *querybuilder.DynamicFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuditUseCase_GetLogsDynamic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogsDynamic'
type MockAuditUseCase_GetLogsDynamic_Call struct {
	*mock.Call
}

// GetLogsDynamic is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *querybuilder.DynamicFilter
func (_e *MockAuditUseCase_Expecter) GetLogsDynamic(ctx interface{}, filter interface{}) *MockAuditUseCase_GetLogsDynamic_Call {
	return &MockAuditUseCase_GetLogsDynamic_Call{Call: _e.mock.On("GetLogsDynamic", ctx, filter)}
}

func (_c *MockAuditUseCase_GetLogsDynamic_Call) Run(run func(ctx context.Context, filter *querybuilder.DynamicFilter)) *MockAuditUseCase_GetLogsDynamic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*querybuilder.DynamicFilter))
	})
	return _c
}

func (_c *MockAuditUseCase_GetLogsDynamic_Call) Return(_a0 []model.AuditLogResponse, _a1 int64, _a2 error) *MockAuditUseCase_GetLogsDynamic_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuditUseCase_GetLogsDynamic_Call) RunAndReturn(run func(context.Context, *querybuilder.DynamicFilter) ([]model.AuditLogResponse, int64, error)) *MockAuditUseCase_GetLogsDynamic_Call {
	_c.Call.Return(run)
	return _c
}

// LogActivity provides a mock function with given fields: ctx, req
func (_m *MockAuditUseCase) LogActivity(ctx context.Context, req model.CreateAuditLogRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for LogActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateAuditLogRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditUseCase_LogActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogActivity'
type MockAuditUseCase_LogActivity_Call struct {
	*mock.Call
}

// LogActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.CreateAuditLogRequest
func (_e *MockAuditUseCase_Expecter) LogActivity(ctx interface{}, req interface{}) *MockAuditUseCase_LogActivity_Call {
	return &MockAuditUseCase_LogActivity_Call{Call: _e.mock.On("LogActivity", ctx, req)}
}

func (_c *MockAuditUseCase_LogActivity_Call) Run(run func(ctx context.Context, req model.CreateAuditLogRequest)) *MockAuditUseCase_LogActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateAuditLogRequest))
	})
	return _c
}

func (_c *MockAuditUseCase_LogActivity_Call) Return(_a0 error) *MockAuditUseCase_LogActivity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditUseCase_LogActivity_Call) RunAndReturn(run func(context.Context, model.CreateAuditLogRequest) error) *MockAuditUseCase_LogActivity_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditUseCase creates a new instance of MockAuditUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditUseCase {
	mock := &MockAuditUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
